#!/usr/bin/env bash
# Regenerate the embedded blob headers from a chip-specific safeboot.bin
# and the new partition CSV.
#
# Tasmota ships pre-built safeboot binaries at variants/tasmota/<chip>-
# safeboot.bin. This script picks the right one based on the CHIP env
# variable (default: tasmota32 = generic ESP32 D0WD).
#
# Usage:
#   ./build_blobs.sh                   # ESP32 D0WD (default)
#   CHIP=tasmota32s3   ./build_blobs.sh
#   CHIP=tasmota32c3   ./build_blobs.sh
#   CHIP=tasmota32c6   ./build_blobs.sh
#
# Or override the source file directly:
#   SAFEBOOT_SRC=/path/to/my/safeboot.bin ./build_blobs.sh
#
# Outputs (in this directory):
#   safeboot.bin              — copy of the picked safeboot, for inspection
#   safeboot_blob.h           — SAFEBOOT_BIN[], SAFEBOOT_LEN, SAFEBOOT_CRC32
#   partitions_new.bin        — binary form of the new CSV (4 KB sector)
#   partitions_blob.h         — PARTITIONS_BIN[], PARTITIONS_LEN, PARTITIONS_CRC32
#
# Hard-fails if any input is missing — the migrator MUST NOT be built
# against stale or absent embedded blobs.

set -euo pipefail
cd "$(dirname "$0")"

CHIP="${CHIP:-tasmota32}"
REPO_ROOT="$(cd ../../.. && pwd)"
SAFEBOOT_SRC="${SAFEBOOT_SRC:-$REPO_ROOT/variants/tasmota/${CHIP}-safeboot.bin}"

if [[ ! -f "$SAFEBOOT_SRC" ]]; then
    echo "ERROR: safeboot binary not found at $SAFEBOOT_SRC"
    echo ""
    echo "Available pre-built safeboot binaries in this repo:"
    ls -1 "$REPO_ROOT/variants/tasmota/"*-safeboot.bin 2>/dev/null | sed 's,.*/,  ,'
    echo ""
    echo "Pick one and re-run:  CHIP=<name-without-suffix> ./build_blobs.sh"
    echo "(e.g. CHIP=tasmota32s3 for ESP32-S3)"
    echo ""
    echo "Or fetch the latest from upstream:"
    echo "  curl -O http://ota.tasmota.com/tasmota32/release/${CHIP}-safeboot.bin"
    exit 1
fi

echo "==> using safeboot: $SAFEBOOT_SRC ($(stat -f%z "$SAFEBOOT_SRC" 2>/dev/null || stat -c%s "$SAFEBOOT_SRC") bytes)"
cp "$SAFEBOOT_SRC" safeboot.bin

[[ -f ../partitions_new.csv ]] || { echo "ERROR: ../partitions_new.csv missing"; exit 1; }

# Find gen_esp32part.py from the user's PlatformIO install.
GENPART="$HOME/.platformio/packages/framework-arduinoespressif32/tools/gen_esp32part.py"
[[ -f "$GENPART" ]] || { echo "ERROR: $GENPART not found — install Arduino-ESP32 via PIO first"; exit 1; }

echo "==> generating partitions_new.bin from CSV"
python3 "$GENPART" ../partitions_new.csv partitions_new.bin

# The partition table goes into a fixed-size 4 KB sector. The generator
# produces a variable-length output (tightly packed entries). Pad with
# 0xFF so the embedded blob is exactly 0x1000 bytes.
echo "==> padding partitions_new.bin to 4 KB"
python3 - <<'PY'
import os
src = open("partitions_new.bin", "rb").read()
if len(src) > 4096:
    raise SystemExit(f"partition table is {len(src)} bytes — too large for one sector")
padded = src + b'\xff' * (4096 - len(src))
open("partitions_new.bin", "wb").write(padded)
PY

# Helper: emit a C header with a uint8_t array, length, and CRC32.
# Uses Python instead of xxd / head trickery for cross-platform portability
# (BSD vs GNU coreutils, missing xxd on minimal Linux installs).
emit_header() {
    local in="$1" symbol="$2" out="$3"
    python3 - "$in" "$symbol" "$out" <<'PY'
import sys, zlib
in_path, symbol, out_path = sys.argv[1:]
data = open(in_path, "rb").read()
crc = zlib.crc32(data) & 0xFFFFFFFF
with open(out_path, "w") as f:
    f.write(f"// Auto-generated by build_blobs.sh — do not edit.\n")
    f.write(f"// Source: {in_path} ({len(data)} bytes, CRC32 0x{crc:08x})\n")
    f.write(f"#pragma once\n")
    f.write(f"#include <stdint.h>\n")
    f.write(f"static const uint32_t {symbol}_LEN   = {len(data)}u;\n")
    f.write(f"static const uint32_t {symbol}_CRC32 = 0x{crc:08x}u;\n")
    f.write(f"static const uint8_t  {symbol}_BIN[{symbol}_LEN] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    f.write(f"}};\n")
print(f"==> {out_path}: {len(data)} bytes, CRC32 0x{crc:08x}")
PY
}

emit_header safeboot.bin       SAFEBOOT       safeboot_blob.h
emit_header partitions_new.bin PARTITIONS     partitions_blob.h

echo "==> done. Now: pio run -d ../"
