// GENERATED by lib2mod.py pass B — scratch buffers moved off
// the (non-existent) plugin .bss into the relocatable PSRAM
// ctx. #included inside matter_ctx_t. DO NOT EDIT.
uint8_t scr_0[qrcodegen_BUFFER_LEN_FOR_VERSION(6)];
char scr_1[16];
char scr_2[8];
char scr_3[24];
uint8_t scr_4[1100];
uint8_t scr_5[1100];
uint8_t scr_6[1280];
uint8_t scr_7[1024];
uint8_t scr_8[1100];
uint8_t scr_9[1280];
uint8_t scr_10[400];
uint8_t scr_11[480];
uint8_t scr_12[480 + 16];
uint8_t scr_13[768];
uint8_t scr_14[768 + 16];
uint8_t scr_15[1024];
uint8_t scr_16[1280];
uint8_t scr_17[1024];
uint8_t scr_18[512];
uint8_t scr_19[1280];
uint8_t scr_20[80];
uint8_t scr_21[1100];
uint8_t scr_22[256];
uint8_t scr_23[160];
uint8_t scr_24[1024];
uint8_t scr_25[8 + 256 + 8 + 64 + 8 + 64 + 8*7 + 65*6 + 32 + 64];
