// matter_c.c — lifecycle skeleton + stubs for the pure-C Matter library.
//
// This file compiles and links today so the host integration (gate,
// xdrv wiring, web page) can be built and exercised before the protocol
// layers exist. Protocol entry points return MATTER_ERR_NOT_IMPLEMENTED.
// Each PLAN.md phase replaces a stub with a real module:
//   Phase 1 -> mtrc_tlv      Phase 3 -> mtrc_spake2p/case/btp/...
//   Phase 4 -> mtrc_im       Phase 5 -> mtrc_ep_* (clusters)
//
// GPLv3. Inspired by Tasmota Berry Matter; implemented from the CSA spec.

#include "matter_c.h"
#include "mtrc_frame.h"
#include "mtrc_pase.h"
#include "mtrc_spake2p.h"
#include "mtrc_crypto.h"
#include "mtrc_sec.h"
#include "mtrc_im.h"
#include "mtrc_dm.h"
#include "mtrc_tlv.h"
#include "mtrc_store.h"
#include "mtrc_case.h"
#include "mtrc_case_msg.h"
#include "mtrc_cert.h"
#include "mtrc_csr.h"
#include "qrcodegen.h"
#ifdef MTRC_ATTEST_TEST_CREDS
#include "mtrc_attest_creds.h"   // generated dev DAC/PAI/CD (gated; never ship)
#endif
#include <string.h>
#include <stdio.h>

// ---- module state ------------------------------------------------------
static struct {
  bool             inited;
  bool             started;
  matter_port_t    port;
  matter_config_t  cfg;
  char             qr[32];     // "MT:..." (built once config is known)
  char             manual[16]; // "1234-567-8901"

  // deferred inbound packet (matter_udp_rx may be called from a network task;
  // the actual crypto-heavy processing runs in matter_loop / main loop).
  volatile bool    rx_pending;
  uint16_t         rx_src_port;
  size_t           rx_len;
  uint8_t          rx_buf[1280];

  // PASE responder session state
  uint8_t          pase_phase;        // 0 idle, 1 sent-resp, 2 sent-pake2, 3 done
  uint16_t         peer_session_id;
  uint16_t         my_session_id;
  uint16_t         exchange_id;
  uint32_t         tx_counter;        // our unsecured-session message counter
  uint8_t          init_random[32];
  uint8_t          resp_random[32];
  uint8_t          salt[16];
  uint32_t         iterations;
  uint8_t          context[32];       // SHA256(prefix || req || resp)
  uint8_t          cA_expected[32];   // prover confirmation we expect in Pake3
  uint8_t          i2r[16], r2i[16], att[16];   // PASE session keys (on success)
  bool             pase_secure;       // true once cA verified
  uint32_t         sec_tx_counter;    // our secured-session message counter
  bool             onoff;             // OnOff attribute (endpoint relay state)
  uint16_t         next_ep;           // next endpoint id handed out by add_endpoint

  // CASE responder state (operational session establishment)
  uint8_t          case_phase;        // 0 idle, 1 sent-sigma2, 2 secure
  uint8_t          case_fabric_index;
  uint16_t         case_peer_sid;     // initiator (controller) session id
  uint16_t         case_my_sid;       // our responder/operational session id
  uint8_t          case_shared[32];   // ECDH shared secret
  uint8_t          case_re_priv[32], case_re_pub[65];  // responder ephemeral
  uint8_t          case_init_eph[65]; // initiator ephemeral pub (from Sigma1)
  uint8_t          case_resp_random[32];
  uint8_t          case_tt[1024];     // transcript: Sigma1[||Sigma2[||Sigma3]]
  size_t           case_tt_len;       // total bytes in case_tt
  size_t           case_len1;         // Sigma1 length (prefix for h1)
  uint8_t          case_i2r[16], case_r2i[16], case_att[16];
  bool             case_secure;
  uint32_t         case_sec_tx_counter;

  // Commissioning: operational keypair generated by CSRRequest, certified by
  // AddNOC (A3). Pending until AddNOC installs the fabric.
  uint8_t          pending_op_priv[32], pending_op_pub[65];
  bool             have_pending_op;
  uint8_t          pending_root_pub[65];      // from AddTrustedRootCertificate
  bool             have_pending_root;

  // single attribute subscription (the report engine)
  bool             sub_active;
  uint32_t         sub_id;
  uint16_t         sub_ep; uint32_t sub_cl, sub_attr;
  uint16_t         sub_max_s;         // max report interval (seconds)
  uint16_t         sub_exch;
  uint32_t         sub_last_ms;       // last report time
  uint64_t         sub_last_val;      // last reported value (change detection)
} g;

static void mlog(matter_log_level_t lvl, const char *msg) {
  if (g.port.log) g.port.log(g.port.ctx, lvl, msg);
}

// ---- onboarding payload (Core Spec §5.1) -------------------------------
// Verhoeff check digit over the decimal string s (manual pairing code).
static uint8_t mtrc_verhoeff(const char *s) {
  static const uint8_t d[10][10] = {
    {0,1,2,3,4,5,6,7,8,9},{1,2,3,4,0,6,7,8,9,5},{2,3,4,0,1,7,8,9,5,6},
    {3,4,0,1,2,8,9,5,6,7},{4,0,1,2,3,9,5,6,7,8},{5,9,8,7,6,0,4,3,2,1},
    {6,5,9,8,7,1,0,4,3,2},{7,6,5,9,8,2,1,0,4,3},{8,7,6,5,9,3,2,1,0,4},
    {9,8,7,6,5,4,3,2,1,0}};
  static const uint8_t p[8][10] = {
    {0,1,2,3,4,5,6,7,8,9},{1,5,7,6,2,8,3,0,9,4},{5,8,0,3,7,9,6,1,4,2},
    {8,9,1,6,0,4,3,5,2,7},{9,4,5,3,1,2,6,8,7,0},{4,2,8,6,5,7,3,9,0,1},
    {2,7,9,3,8,0,6,4,1,5},{7,0,4,6,9,1,3,2,5,8}};
  static const uint8_t inv[10] = {0,4,3,2,1,5,6,7,8,9};
  int c = 0, len = (int)strlen(s);
  for (int i = 0; i < len; i++) {
    int dig = s[len - 1 - i] - '0';
    c = d[c][p[(i + 1) % 8][dig]];
  }
  return inv[c];
}

// QR module matrix for the onboarding payload, so the host can draw the code
// itself (no external/CDN QR library). Encoded once from g.qr.
static uint8_t g_qrbuf[qrcodegen_BUFFER_LEN_FOR_VERSION(6)];
static int     g_qr_ok = 0;

// Build the manual pairing code (11 digits) and the "MT:" QR string into g.
static void mtrc_build_onboarding(void) {
  uint16_t disc = g.cfg.discriminator & 0x0FFF;
  uint32_t pass = g.cfg.passcode & 0x07FFFFFF;

  // Manual code (short, no VID/PID): d1 | chunk2(5) | chunk3(4) | Verhoeff.
  unsigned d1 = (0u << 2) | (unsigned)(disc >> 10);
  unsigned c2 = ((unsigned)(disc & 0x300) << 6) | (unsigned)(pass & 0x3FFF);
  unsigned c3 = (unsigned)(pass >> 14);
  char body[12];
  snprintf(body, sizeof(body), "%01u%05u%04u", d1, c2, c3);
  snprintf(g.manual, sizeof(g.manual), "%s%u", body, (unsigned)mtrc_verhoeff(body));

  // QR: bit-pack version(3)=0, VID(16), PID(16), flow(2)=0, discovery(8),
  // discriminator(12), passcode(27), pad(4) = 88 bits, then Base38 + "MT:".
  uint8_t buf[11]; memset(buf, 0, sizeof(buf));
  int pos = 0;
  #define MTRC_PUTBITS(val, ln) do { \
      for (int _i = 0; _i < (ln); _i++) { \
        if ((uint32_t)(val) & (1u << _i)) buf[pos >> 3] |= (1 << (pos & 7)); \
        pos++; } } while (0)
  MTRC_PUTBITS(0, 3);
  MTRC_PUTBITS(g.cfg.vendor_id, 16);
  MTRC_PUTBITS(g.cfg.product_id, 16);
  MTRC_PUTBITS(0, 2);                 // commissioning flow = standard
  MTRC_PUTBITS(0x04, 8);             // discovery capabilities = on-network/IP
  MTRC_PUTBITS(disc, 12);
  MTRC_PUTBITS(pass, 27);
  MTRC_PUTBITS(0, 4);               // padding
  #undef MTRC_PUTBITS
  static const char B38[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-.";
  char *o = g.qr; *o++ = 'M'; *o++ = 'T'; *o++ = ':';
  for (int i = 0; i < 11; i += 3) {
    int cl = (11 - i >= 3) ? 3 : (11 - i);
    uint32_t v = 0;
    for (int j = 0; j < cl; j++) v |= (uint32_t)buf[i + j] << (8 * j);
    int nch = (cl == 3) ? 5 : (cl == 2) ? 4 : 2;
    for (int k = 0; k < nch; k++) { *o++ = B38[v % 38]; v /= 38; }
  }
  *o = '\0';

  // Pre-render the QR module matrix so the host can draw it without a CDN.
  static uint8_t tmp[qrcodegen_BUFFER_LEN_FOR_VERSION(6)];
  g_qr_ok = qrcodegen_encodeText(g.qr, tmp, g_qrbuf, qrcodegen_Ecc_MEDIUM,
                                 qrcodegen_VERSION_MIN, 6, qrcodegen_Mask_AUTO, true);
}

int matter_qr_size(void) { return g_qr_ok ? qrcodegen_getSize(g_qrbuf) : 0; }
bool matter_qr_dark(int x, int y) {
  return g_qr_ok ? qrcodegen_getModule(g_qrbuf, x, y) : false;
}

// Cluster ids used by the data model.
#define MTRC_CL_ONOFF       0x0006
#define MTRC_CL_LEVEL       0x0008
#define MTRC_CL_DESCRIPTOR  0x001D
#define MTRC_CL_BASIC_INFO  0x0028
#define MTRC_CL_TEMP_MEAS   0x0402
#define MTRC_CL_HUM_MEAS    0x0405

// Attach a device-type's default clusters/attributes to an endpoint. Keeps the
// per-device-type mandatory set in one place so matter_add_endpoint and the
// matter_init seed agree. (Subset; extended as Phase D clusters land.)
static void dm_attach_device_type(uint16_t ep, uint32_t dt) {
  switch (dt) {
    case MATTER_DEVTYPE_ON_OFF_PLUGIN:
    case MATTER_DEVTYPE_ON_OFF_LIGHT:
      mtrc_dm_add_attr(ep, MTRC_CL_ONOFF, 0x0000, MTRC_DM_T_BOOL,
                       MTRC_DM_F_WRITABLE | MTRC_DM_F_LIVE, 0);
      break;
    case MATTER_DEVTYPE_DIMMABLE_LIGHT:
      mtrc_dm_add_attr(ep, MTRC_CL_ONOFF, 0x0000, MTRC_DM_T_BOOL,
                       MTRC_DM_F_WRITABLE | MTRC_DM_F_LIVE, 0);
      mtrc_dm_add_attr(ep, MTRC_CL_LEVEL, 0x0000, MTRC_DM_T_U8,
                       MTRC_DM_F_WRITABLE, 0);   // CurrentLevel
      break;
    case MATTER_DEVTYPE_TEMP_SENSOR:
      mtrc_dm_add_attr(ep, MTRC_CL_TEMP_MEAS, 0x0000, MTRC_DM_T_U16, 0, 0);
      break;
    case MATTER_DEVTYPE_HUMIDITY_SENSOR:
      mtrc_dm_add_attr(ep, MTRC_CL_HUM_MEAS, 0x0000, MTRC_DM_T_U16, 0, 0);
      break;
    default: break;
  }
}

#ifdef MTRC_CASE_TEST_FABRIC
// Pre-provision a fixed TEST fabric so the CASE responder can establish an
// operational session before the real commissioning flow (A2/A3) exists. The
// matching credentials live in the Python prover. Gated OFF by default — never
// ship test keys; enable via -DMTRC_CASE_TEST_FABRIC for the device test only.
static void case_seed_test_fabric(void) {
  if (mtrc_store_count() > 0) return;
  mtrc_fabric *f = mtrc_store_alloc();
  if (!f) return;
  f->fabric_id = 0x0000FAB000000001ULL;
  f->node_id   = 0x1122334455667788ULL;
  f->admin_vendor_id = 0xFFF1;
  memset(f->ipk, 0xC5, 16);
  uint8_t root_priv[32]; memset(root_priv, 0x07, 32);
  mtrc_ec_pub_from_priv(f->root_pub, root_priv);
  memset(f->op_priv, 0x11, 32);
  mtrc_ec_pub_from_priv(f->op_pub, f->op_priv);
  for (int i = 0; i < 48; i++) f->noc[i] = (uint8_t)(0x40 + i);
  f->noc_len = 48;
  mlog(MATTER_LOG_INFO, "CASE: seeded TEST fabric (do not ship)");
}
#endif

// Seed endpoint 0 (root node): Descriptor + Basic Information VID/PID.
static void dm_seed_root(void) {
  mtrc_dm_add_endpoint(0, 0x0016);   // Root Node device type
  mtrc_dm_add_cluster(0, MTRC_CL_DESCRIPTOR);   // mandatory on every endpoint
  mtrc_dm_add_attr(0, MTRC_CL_BASIC_INFO, 0x0002, MTRC_DM_T_U16, 0, g.cfg.vendor_id);
  mtrc_dm_add_attr(0, MTRC_CL_BASIC_INFO, 0x0004, MTRC_DM_T_U16, 0, g.cfg.product_id);
}

// ---- lifecycle ---------------------------------------------------------
matter_err_t matter_init(const matter_port_t *port, const matter_config_t *cfg) {
  if (!port || !cfg) return MATTER_ERR_INVALID_ARG;
  // Minimum viable port: persistence + time + entropy must be present.
  if (!port->kv_get || !port->kv_set || !port->millis || !port->random_bytes)
    return MATTER_ERR_INVALID_ARG;

  memset(&g, 0, sizeof(g));
  g.port = *port;
  g.cfg  = *cfg;
  g.inited = true;
  g.next_ep = 1;            // endpoint 0 is the root node

  // Seed the data-model registry: root node + a default OnOff endpoint so the
  // current relay device works out of the box. A TinyC script (Phase C) can
  // matter_factory_reset() and rebuild a different model.
  mtrc_dm_reset();
  dm_seed_root();
  matter_add_endpoint(MATTER_DEVTYPE_ON_OFF_PLUGIN);   // -> endpoint 1

  // Fabric table (operational credentials). Empty until commissioned (A2/A3);
  // a fixed test fabric can be pre-provisioned for the CASE responder test.
  mtrc_store_reset();
#ifdef MTRC_CASE_TEST_FABRIC
  case_seed_test_fabric();
#endif

  // Onboarding payload: QR ("MT:...") + 11-digit manual pairing code.
  mtrc_build_onboarding();

  mlog(MATTER_LOG_INFO, "matter_c init (data model seeded)");
  return MATTER_OK;
}

#define MTRC_COMMISSION_PORT 5540   // Matter operational/commissioning UDP port

matter_err_t matter_start(void) {
  if (!g.inited)   return MATTER_ERR_NOT_INIT;
  if (g.started)   return MATTER_OK;

  // Publish the commissionable node over mDNS (_matterc._udp) so an
  // on-network commissioner (chip-tool `pairing onnetwork`) can discover us.
  // TXT keys per Matter Core Spec §4.3.1: D=discriminator, CM=commissioning
  // mode, VP=vendor+product. (UDP listener + PASE handling come next.)
  if (g.port.mdns_publish) {
    static char txt_d[16], txt_cm[8], txt_vp[24];
    snprintf(txt_d,  sizeof(txt_d),  "D=%u", (unsigned)g.cfg.discriminator);
    snprintf(txt_cm, sizeof(txt_cm), "CM=1");   // 1 = in commissioning mode
    snprintf(txt_vp, sizeof(txt_vp), "VP=%u+%u", (unsigned)g.cfg.vendor_id,
             (unsigned)g.cfg.product_id);
    const char *txt[] = { txt_d, txt_cm, txt_vp };

    // 64-bit commissioning instance name as 16 uppercase hex (Matter spec).
    uint8_t inst[8] = {0};
    if (g.port.random_bytes) g.port.random_bytes(g.port.ctx, inst, 8);
    char instance[17];
    for (int i = 0; i < 8; i++) snprintf(instance + 2*i, 3, "%02X", inst[i]);

    matter_err_t e = g.port.mdns_publish(g.port.ctx, "matterc", instance,
                                         MTRC_COMMISSION_PORT, txt, 3);
    mlog(e == MATTER_OK ? MATTER_LOG_INFO : MATTER_LOG_ERROR,
         e == MATTER_OK ? "matter_c: commissionable mDNS published (_matterc._udp)"
                        : "matter_c: mDNS publish failed");
  } else {
    mlog(MATTER_LOG_INFO, "matter_c start — no mdns_publish port; not discoverable");
  }

  g.started = true;
  // PASE-over-UDP commissioning is the next milestone; discovery is live.
  return MATTER_OK;
}

matter_err_t matter_stop(void) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  g.started = false;
  mlog(MATTER_LOG_INFO, "matter_c stop (stub)");
  return MATTER_OK;
}

matter_err_t matter_factory_reset(void) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  // TODO Phase 3: enumerate + delete fabric/session keys via port.kv_del.
  mlog(MATTER_LOG_INFO, "matter_c factory reset (stub)");
  return MATTER_ERR_NOT_IMPLEMENTED;
}

// ---- PASE responder ----------------------------------------------------
// Send a Secure Channel message on the unsecured session (id 0). The
// response always reflects the initiator's exchange and (optionally) acks.
static void pase_send(uint8_t opcode, const uint8_t *payload, size_t plen,
                      bool has_ack, uint32_t ack_counter, bool reliable) {
  mtrc_msg_header mh; memset(&mh, 0, sizeof(mh));
  mh.session_id = 0; mh.session_type = 0; mh.msg_counter = ++g.tx_counter;
  mtrc_proto_header ph; memset(&ph, 0, sizeof(ph));
  ph.initiator   = false;          // we are the responder
  ph.ack         = has_ack;
  ph.ack_counter = ack_counter;
  ph.reliability = reliable;
  ph.opcode      = opcode;
  ph.exchange_id = g.exchange_id;
  ph.protocol_id = MTRC_PROTO_SECURE_CHANNEL;
  uint8_t out[1280];
  int n = mtrc_frame_encode(out, sizeof(out), &mh, &ph, payload, plen);
  if (n > 0 && g.port.udp_send)
    g.port.udp_send(g.port.ctx, NULL, 0, out, (size_t)n);
}

// PBKDFParamRequest -> PBKDFParamResponse (we choose salt + iterations).
static void pase_handle_param_req(const uint8_t *payload, size_t plen,
                                  const mtrc_msg_header *mh) {
  mtrc_pase_param_req req;
  if (!mtrc_pase_decode_param_req(payload, plen, &req)) return;
  g.peer_session_id = req.initiator_session_id;
  memcpy(g.init_random, req.initiator_random, 32);

  g.port.random_bytes(g.port.ctx, g.resp_random, 32);
  g.port.random_bytes(g.port.ctx, g.salt, 16);
  uint16_t sid = 0;
  g.port.random_bytes(g.port.ctx, (uint8_t *)&sid, 2);
  g.my_session_id = sid ? sid : 1;
  g.iterations = 1000;

  mtrc_pase_param_resp resp; memset(&resp, 0, sizeof(resp));
  memcpy(resp.initiator_random, req.initiator_random, 32);
  memcpy(resp.responder_random, g.resp_random, 32);
  resp.responder_session_id = g.my_session_id;
  resp.iterations = g.iterations;
  memcpy(resp.salt, g.salt, 16); resp.salt_len = 16;

  uint8_t rp[160];
  int rn = mtrc_pase_encode_param_resp(rp, sizeof(rp), &resp);
  if (rn < 0) return;

  // SPAKE2+ transcript context = SHA256(prefix || req || resp), saved for Pake.
  mtrc_pase_context(payload, plen, rp, (size_t)rn, g.context);

  pase_send(MTRC_SC_PBKDF_PARAM_RSP, rp, (size_t)rn, true, mh->msg_counter, true);
  g.pase_phase = 1;
  mlog(MATTER_LOG_INFO, "PASE: PBKDFParamResponse sent");
}

// Pake1 (pA) -> Pake2 (pB, cB). Verifier-side SPAKE2+ (heavy: PBKDF2 + EC).
static void pase_handle_pake1(const uint8_t *payload, size_t plen,
                              const mtrc_msg_header *mh) {
  uint8_t pA[65];
  if (!mtrc_pase_decode_pake1(payload, plen, pA)) return;

  uint8_t w0[32], w1[32], L[65], y[32], pB[65], Z[65], V[65];
  if (!mtrc_pase_derive_w0w1(g.cfg.passcode, g.salt, 16, g.iterations, w0, w1)) return;
  if (!mtrc_ec_mulgen(L, w1, 32)) return;                      // L = w1*G
  g.port.random_bytes(g.port.ctx, y, 32);
  if (!mtrc_spake2p_verifier_Y(w0, y, pB)) return;             // pB = y*G + w0*N
  if (!mtrc_spake2p_verifier_ZV(w0, y, pA, L, Z, V)) return;   // Z,V from pA,L

  mtrc_pase_keys_t k;
  if (!mtrc_pase_keys(g.context, pA, pB, Z, V, w0, &k)) return;
  memcpy(g.cA_expected, k.cA, 32);                             // expect this in Pake3
  memcpy(g.i2r, k.i2r, 16); memcpy(g.r2i, k.r2i, 16); memcpy(g.att, k.att, 16);

  uint8_t out[160];
  int n = mtrc_pase_encode_pake2(out, sizeof(out), pB, k.cB);  // send pB + cB
  if (n < 0) return;
  pase_send(MTRC_SC_PASE_PAKE2, out, (size_t)n, true, mh->msg_counter, true);
  g.pase_phase = 2;
  mlog(MATTER_LOG_INFO, "PASE: Pake2 sent (SPAKE2+ verifier)");
}

// Pake3 (cA) -> verify, then StatusReport. On success the PASE session keys
// are live (g.i2r / g.r2i / g.att).
static void pase_handle_pake3(const uint8_t *payload, size_t plen,
                              const mtrc_msg_header *mh) {
  uint8_t cA[32];
  if (!mtrc_pase_decode_pake3(payload, plen, cA)) return;
  uint8_t diff = 0;
  for (int i = 0; i < 32; i++) diff |= (uint8_t)(cA[i] ^ g.cA_expected[i]);

  // Secure Channel StatusReport: GeneralCode(2) | ProtocolId(4) | Code(2), LE.
  uint8_t sr[8]; memset(sr, 0, 8);
  if (diff == 0) {
    // GeneralCode=0 (Success), ProtocolId=0 (SecureChannel),
    // Code=0 (SessionEstablishmentSuccess)
    g.pase_secure = true; g.pase_phase = 3;
    pase_send(MTRC_SC_STATUS_REPORT, sr, 8, true, mh->msg_counter, true);
    mlog(MATTER_LOG_INFO, "PASE: cA verified -> SESSION ESTABLISHED (StatusReport success)");
  } else {
    sr[0] = 0x01;   // GeneralCode = 1 (Failure)
    pase_send(MTRC_SC_STATUS_REPORT, sr, 8, true, mh->msg_counter, true);
    g.pase_phase = 0;
    mlog(MATTER_LOG_ERROR, "PASE: cA MISMATCH -> StatusReport failure");
  }
}

// ---- CASE responder (operational session establishment) ----------------
// Raw AES-CCM seal/open for the CASE TBE blobs: blob = ciphertext || tag,
// AAD empty (Core Spec §4.13.2). Returns 1 on success.
static int case_seal(const uint8_t key[16], const uint8_t nonce[13],
                     const uint8_t *pt, size_t pt_len, uint8_t *out) {
  memcpy(out, pt, pt_len);
  return mtrc_aes_ccm_encrypt(key, nonce, 13, NULL, 0, out, pt_len, out + pt_len, 16);
}
static int case_open(const uint8_t key[16], const uint8_t nonce[13],
                     const uint8_t *blob, size_t blob_len, uint8_t *out) {
  if (blob_len < 16) return 0;
  size_t ct = blob_len - 16;
  memcpy(out, blob, ct);
  return mtrc_aes_ccm_decrypt(key, nonce, 13, NULL, 0, out, ct, blob + ct, 16);
}

// Sigma1 -> Sigma2. Match destinationId to a stored fabric, do ECDH, seal our
// NOC + a signature over TBSData2 with the operational key, send Sigma2.
static void case_handle_sigma1(const uint8_t *pl, size_t pll,
                               const mtrc_msg_header *mh) {
  mtrc_sigma1 s1;
  if (!mtrc_sigma1_decode(pl, pll, &s1)) return;

  mtrc_fabric *f = NULL; uint8_t cand[32];
  for (int i = 0; i < mtrc_store_count(); i++) {
    mtrc_fabric *cf = mtrc_store_at(i);
    mtrc_case_destination_id(cf->ipk, s1.initiator_random, cf->root_pub,
                             cf->fabric_id, cf->node_id, cand);
    if (memcmp(cand, s1.destination_id, 32) == 0) { f = cf; break; }
  }
  if (!f) { mlog(MATTER_LOG_ERROR, "CASE: no fabric matches destinationId"); return; }

  g.case_fabric_index = f->fabric_index;
  g.case_peer_sid = s1.initiator_session_id;
  memcpy(g.case_init_eph, s1.initiator_eph_pub, 65);   // needed for Sigma3 verify
  g.port.random_bytes(g.port.ctx, g.case_re_priv, 32);
  if (!mtrc_ec_pub_from_priv(g.case_re_pub, g.case_re_priv)) return;
  g.port.random_bytes(g.port.ctx, g.case_resp_random, 32);
  uint16_t sid = 0; g.port.random_bytes(g.port.ctx, (uint8_t *)&sid, 2);
  g.case_my_sid = sid ? sid : 2;
  if (!mtrc_ecdh(g.case_shared, s1.initiator_eph_pub, g.case_re_priv)) return;

  if (pll > sizeof(g.case_tt)) return;
  memcpy(g.case_tt, pl, pll); g.case_tt_len = pll; g.case_len1 = pll;
  uint8_t h1[32]; mtrc_sha256(g.case_tt, g.case_len1, h1);

  uint8_t s2k[16];
  if (!mtrc_case_s2k(g.case_shared, f->ipk, g.case_resp_random, g.case_re_pub, h1, s2k))
    return;

  static uint8_t tmp[600];
  mtrc_case_tbs tbs; memset(&tbs, 0, sizeof(tbs));
  tbs.noc = f->noc; tbs.noc_len = f->noc_len;
  memcpy(tbs.sender_pub, g.case_re_pub, 65);
  memcpy(tbs.receiver_pub, s1.initiator_eph_pub, 65);
  int nt = mtrc_case_tbs_encode(tmp, sizeof(tmp), &tbs);
  if (nt < 0) return;
  uint8_t ht[32]; mtrc_sha256(tmp, (size_t)nt, ht);

  mtrc_case_tbe tbe; memset(&tbe, 0, sizeof(tbe));
  tbe.noc = f->noc; tbe.noc_len = f->noc_len;
  if (!mtrc_ecdsa_sign(tbe.signature, ht, f->op_priv)) return;
  int ne = mtrc_case_tbe_encode(tmp, sizeof(tmp), &tbe);
  if (ne < 0) return;

  static uint8_t enc2[700];
  if (!case_seal(s2k, MTRC_CASE_NONCE_SIGMA2, tmp, (size_t)ne, enc2)) return;

  mtrc_sigma2 s2; memset(&s2, 0, sizeof(s2));
  memcpy(s2.responder_random, g.case_resp_random, 32);
  s2.responder_session_id = g.case_my_sid;
  memcpy(s2.responder_eph_pub, g.case_re_pub, 65);
  s2.encrypted2 = enc2; s2.encrypted2_len = (size_t)ne + 16;
  static uint8_t s2buf[800];
  int n2 = mtrc_sigma2_encode(s2buf, sizeof(s2buf), &s2);
  if (n2 < 0) return;
  if (g.case_tt_len + (size_t)n2 <= sizeof(g.case_tt)) {
    memcpy(g.case_tt + g.case_tt_len, s2buf, n2); g.case_tt_len += (size_t)n2;
  }
  pase_send(MTRC_SC_CASE_SIGMA2, s2buf, (size_t)n2, true, mh->msg_counter, true);
  g.case_phase = 1;
  mlog(MATTER_LOG_INFO, "CASE: Sigma2 sent (responder authenticated)");
}

// Sigma3 -> operational session. Decrypt TBEData3, verify the initiator's
// signature with the public key from its NOC, derive the session keys.
static void case_handle_sigma3(const uint8_t *pl, size_t pll,
                               const mtrc_msg_header *mh) {
  if (g.case_phase != 1) return;
  mtrc_fabric *f = mtrc_store_by_index(g.case_fabric_index);
  if (!f) return;
  mtrc_sigma3 s3;
  if (!mtrc_sigma3_decode(pl, pll, &s3)) return;

  // h12 = SHA256(Sigma1||Sigma2): case_tt currently holds exactly those two.
  uint8_t h12[32]; mtrc_sha256(g.case_tt, g.case_tt_len, h12);
  uint8_t s3k[16];
  if (!mtrc_case_s3k(g.case_shared, f->ipk, h12, s3k)) return;

  static uint8_t tbe3[512];
  if (!case_open(s3k, MTRC_CASE_NONCE_SIGMA3, s3.encrypted3, s3.encrypted3_len, tbe3)) {
    mlog(MATTER_LOG_ERROR, "CASE: Sigma3 TBE decrypt failed"); return;
  }
  mtrc_case_tbe t3;
  if (!mtrc_case_tbe_decode(tbe3, s3.encrypted3_len - 16, &t3)) return;

  // Verify the initiator's signature over TBSData3 with its NOC public key.
  // Relaxed for first interop: full cert-chain verify (A1b) is a later step;
  // here we parse the NOC (A1a) for its pubkey and check the Sigma3 signature.
  mtrc_cert nc; int verified = 0;
  if (mtrc_cert_parse(t3.noc, t3.noc_len, &nc) && nc.have_pubkey) {
    mtrc_case_tbs tbs; memset(&tbs, 0, sizeof(tbs));
    tbs.noc = t3.noc; tbs.noc_len = t3.noc_len;
    memcpy(tbs.sender_pub, g.case_init_eph, 65);   // initiator was sender
    memcpy(tbs.receiver_pub, g.case_re_pub, 65);
    static uint8_t tmp[600];
    int nt = mtrc_case_tbs_encode(tmp, sizeof(tmp), &tbs);
    if (nt > 0) {
      uint8_t ht[32]; mtrc_sha256(tmp, (size_t)nt, ht);
      verified = mtrc_ecdsa_verify(t3.signature, ht, nc.pubkey);
    }
  }
  if (!verified) {
    mlog(MATTER_LOG_ERROR, "CASE: initiator NOC signature INVALID");
    uint8_t sr[8]; memset(sr, 0, 8); sr[0] = 0x01;   // GeneralCode = Failure
    pase_send(MTRC_SC_STATUS_REPORT, sr, 8, true, mh->msg_counter, true);
    g.case_phase = 0;
    return;
  }

  // Append Sigma3 to the transcript, derive the operational session keys.
  if (g.case_tt_len + pll <= sizeof(g.case_tt)) {
    memcpy(g.case_tt + g.case_tt_len, pl, pll); g.case_tt_len += pll;
  }
  uint8_t hall[32]; mtrc_sha256(g.case_tt, g.case_tt_len, hall);
  if (!mtrc_case_session_keys(g.case_shared, f->ipk, hall,
                              g.case_i2r, g.case_r2i, g.case_att)) return;
  g.case_secure = true; g.case_phase = 2; g.case_sec_tx_counter = 0;

  uint8_t sr[8]; memset(sr, 0, 8);   // GeneralCode = Success
  pase_send(MTRC_SC_STATUS_REPORT, sr, 8, true, mh->msg_counter, true);
  mlog(MATTER_LOG_INFO, "CASE: Sigma3 verified -> OPERATIONAL SESSION ESTABLISHED");
}

// Active secure-session TX context (PASE or CASE), selected before each
// dispatch / report so secured_send addresses the right session id, response
// key (R2I) and message counter.
static struct { const uint8_t *key; uint16_t sid; uint32_t *ctr; } g_tx =
  { NULL, 0, NULL };
static void tx_use_pase(void) {
  g_tx.key = g.r2i; g_tx.sid = g.peer_session_id; g_tx.ctr = &g.sec_tx_counter;
}
static void tx_use_case(void) {
  g_tx.key = g.case_r2i; g_tx.sid = g.case_peer_sid; g_tx.ctr = &g.case_sec_tx_counter;
}

// Send an encrypted message on the active secured session (PASE or CASE):
// the R2I key, our session-id assigned to the peer, our secured counter,
// acking the inbound message.
static void secured_send(uint8_t opcode, uint16_t protocol_id,
                         const uint8_t *payload, size_t plen,
                         uint16_t exch, bool has_ack, uint32_t ack_counter) {
  if (!g_tx.key || !g_tx.ctr) return;
  mtrc_msg_header mh; memset(&mh, 0, sizeof(mh));
  mh.session_id = g_tx.sid; mh.session_type = 0;
  mh.msg_counter = ++(*g_tx.ctr);
  mtrc_proto_header ph; memset(&ph, 0, sizeof(ph));
  ph.initiator = false; ph.ack = has_ack; ph.ack_counter = ack_counter;
  ph.reliability = true; ph.opcode = opcode; ph.exchange_id = exch;
  ph.protocol_id = protocol_id;
  static uint8_t out[1280];
  int n = mtrc_sec_encode(out, sizeof(out), &mh, &ph, payload, plen, g_tx.key);
  if (n > 0 && g.port.udp_send)
    g.port.udp_send(g.port.ctx, NULL, 0, out, (size_t)n);
}

// Live value of an attribute. Resolution order:
//   1. host's on_attr_read (the firmware owns it, e.g. the real relay state),
//   2. the data-model registry (script/host-pushed cache),
//   3. legacy fallbacks (kept until every attribute is registered).
static uint64_t attr_value(uint16_t ep, uint32_t cl, uint32_t attr) {
  uint64_t v = 0;
  if (g.port.on_attr_read &&
      g.port.on_attr_read(g.port.ctx, ep, cl, attr, &v) == MATTER_OK) return v;
  if (mtrc_dm_get(ep, cl, attr, &v)) return v;
  if      (cl == 0x0006 && attr == 0x0000) v = g.onoff ? 1 : 0;
  else if (cl == 0x0028 && attr == 0x0002) v = g.cfg.vendor_id;
  else if (cl == 0x0028 && attr == 0x0004) v = g.cfg.product_id;
  return v;
}

// Extract a context-tagged field from the first command's CommandFields in an
// InvokeRequest (msg struct -> ctx2 array -> CommandDataIB -> ctx1 fields).
// want_bytes: 1 -> fill *bp/*blen (BYTES); 0 -> fill *uv (UINT). Returns 1/0.
static int inv_field(const uint8_t *buf, size_t len, uint32_t tag, int want_bytes,
                     const uint8_t **bp, size_t *blen, uint64_t *uv) {
  mtrc_tlv_reader r; mtrc_tlv_reader_init(&r, buf, len);
  mtrc_tlv_elem e;
  if (!mtrc_tlv_read(&r, &e) || e.type != MTRC_TLV_STRUCT) return 0;  // message
  int depth = 1;
  while (depth >= 1 && mtrc_tlv_read(&r, &e)) {
    if (e.type == MTRC_TLV_END) { depth--; continue; }
    if (depth == 1 && e.tag.ctrl == MTRC_TLV_TAG_CONTEXT && e.tag.number == 2 &&
        e.type == MTRC_TLV_ARRAY) {                       // InvokeRequests
      mtrc_tlv_elem c;
      if (!mtrc_tlv_read(&r, &c) || c.type != MTRC_TLV_STRUCT) return 0;  // CommandDataIB
      int d2 = 1;
      while (d2 >= 1 && mtrc_tlv_read(&r, &c)) {
        if (c.type == MTRC_TLV_END) { d2--; continue; }
        if (d2 == 1 && c.tag.ctrl == MTRC_TLV_TAG_CONTEXT && c.tag.number == 1 &&
            c.type == MTRC_TLV_STRUCT) {                  // CommandFields
          mtrc_tlv_elem f;
          while (mtrc_tlv_read(&r, &f) && f.type != MTRC_TLV_END) {
            if (f.tag.ctrl == MTRC_TLV_TAG_CONTEXT && f.tag.number == tag) {
              if (want_bytes && f.type == MTRC_TLV_BYTES) { *bp = f.bytes; *blen = f.bytes_len; return 1; }
              if (!want_bytes && f.type == MTRC_TLV_UINT)  { *uv = f.u; return 1; }
            }
          }
          return 0;
        }
        if (c.type==MTRC_TLV_STRUCT||c.type==MTRC_TLV_ARRAY||c.type==MTRC_TLV_LIST) d2++;
      }
      return 0;
    }
    if (e.type==MTRC_TLV_STRUCT||e.type==MTRC_TLV_ARRAY||e.type==MTRC_TLV_LIST) depth++;
  }
  return 0;
}

// Build a CSRResponse (NOC cluster cmd 0x05): generate a fresh operational
// keypair, a PKCS#10 CSR for it, and the NOCSRElements{1:csr,2:CSRNonce} plus
// an attestationSignature over (NOCSRElements || attestationChallenge). The
// DAC key is a placeholder until A2 supplies the real device DAC. Returns the
// InvokeResponse length, or -1.
static int build_csr_response(uint8_t *out, size_t cap, uint16_t ep, uint32_t cl,
                              const uint8_t *nonce, size_t nlen) {
  g.port.random_bytes(g.port.ctx, g.pending_op_priv, 32);
  if (!mtrc_ec_pub_from_priv(g.pending_op_pub, g.pending_op_priv)) return -1;
  g.have_pending_op = true;

  static uint8_t csr[400];
  int csrlen = mtrc_csr_build(csr, sizeof(csr), g.pending_op_priv, g.pending_op_pub);
  if (csrlen < 0) return -1;

  static uint8_t nocsr[480];
  mtrc_tlv_writer w; mtrc_tlv_writer_init(&w, nocsr, sizeof(nocsr));
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(1), csr, (size_t)csrlen);
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(2), nonce, nlen);
  mtrc_tlv_end_container(&w);
  if (!mtrc_tlv_writer_ok(&w)) return -1;
  size_t nocsr_len = mtrc_tlv_writer_len(&w);

  // attestationSignature = ECDSA(DAC, SHA256(NOCSRElements || attChallenge)).
  // attChallenge is the PASE/CASE Att key. DAC is a placeholder until A2.
  uint8_t dac[32]; memset(dac, 0x55, 32);
  static uint8_t hin[480 + 16];
  memcpy(hin, nocsr, nocsr_len); memcpy(hin + nocsr_len, g.att, 16);
  uint8_t h[32]; mtrc_sha256(hin, nocsr_len + 16, h);
  uint8_t attsig[64]; if (!mtrc_ecdsa_sign(attsig, h, dac)) return -1;

  mtrc_tlv_writer_init(&w, out, cap);
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());          // InvokeResponseMessage
  mtrc_tlv_put_bool(&w, mtrc_tlv_ctx(0), false);
  mtrc_tlv_start_array(&w, mtrc_tlv_ctx(1));           // InvokeResponses
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());          //  InvokeResponseIB
  mtrc_tlv_start_struct(&w, mtrc_tlv_ctx(0));          //   command CommandDataIB
  mtrc_tlv_start_list(&w, mtrc_tlv_ctx(0));            //    CommandPath
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0), ep);
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(1), cl);
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(2), 0x05);        //    CSRResponse
  mtrc_tlv_end_container(&w);
  mtrc_tlv_start_struct(&w, mtrc_tlv_ctx(1));          //    CommandFields
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(0), nocsr, nocsr_len);   // NOCSRElements
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(1), attsig, 64);         // attestationSignature
  mtrc_tlv_end_container(&w);
  mtrc_tlv_end_container(&w);                          //   end CommandDataIB
  mtrc_tlv_end_container(&w);                          //  end InvokeResponseIB
  mtrc_tlv_end_container(&w);                          // end InvokeResponses
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0xFF), 1);
  mtrc_tlv_end_container(&w);
  return mtrc_tlv_writer_ok(&w) ? (int)mtrc_tlv_writer_len(&w) : -1;
}

#ifdef MTRC_ATTEST_TEST_CREDS
// Build an InvokeResponse carrying a command (resp_cmd) whose CommandFields are
// one or two byte strings: {0:f0} and (if f1) {1:f1}. Covers CertificateChain
// Response, AttestationResponse, and similar. Returns length, or -1.
static int build_cmd_resp_bytes(uint8_t *out, size_t cap, uint16_t ep, uint32_t cl,
                                uint32_t resp_cmd,
                                const uint8_t *f0, size_t f0len,
                                const uint8_t *f1, size_t f1len) {
  mtrc_tlv_writer w; mtrc_tlv_writer_init(&w, out, cap);
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());          // InvokeResponseMessage
  mtrc_tlv_put_bool(&w, mtrc_tlv_ctx(0), false);
  mtrc_tlv_start_array(&w, mtrc_tlv_ctx(1));           // InvokeResponses
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());          //  InvokeResponseIB
  mtrc_tlv_start_struct(&w, mtrc_tlv_ctx(0));          //   command CommandDataIB
  mtrc_tlv_start_list(&w, mtrc_tlv_ctx(0));            //    CommandPath
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0), ep);
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(1), cl);
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(2), resp_cmd);
  mtrc_tlv_end_container(&w);
  mtrc_tlv_start_struct(&w, mtrc_tlv_ctx(1));          //    CommandFields
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(0), f0, f0len);
  if (f1) mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(1), f1, f1len);
  mtrc_tlv_end_container(&w);
  mtrc_tlv_end_container(&w);                          //   end CommandDataIB
  mtrc_tlv_end_container(&w);                          //  end InvokeResponseIB
  mtrc_tlv_end_container(&w);                          // end InvokeResponses
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0xFF), 1);
  mtrc_tlv_end_container(&w);
  return mtrc_tlv_writer_ok(&w) ? (int)mtrc_tlv_writer_len(&w) : -1;
}
#endif  // MTRC_ATTEST_TEST_CREDS

// AttestationRequest -> AttestationResponse (cmd 0x01): attestationElements =
// {1:CD, 2:nonce, 3:timestamp}; attestationSignature = ECDSA(DAC, SHA256(
// attestationElements || attestationChallenge)). The challenge is the PASE
// Att key (g.att). DAC/CD come from the gated dev cred set (A2).
static int build_attestation_response(uint8_t *out, size_t cap, uint16_t ep,
                                      uint32_t cl, const uint8_t *nonce, size_t nlen) {
#ifdef MTRC_ATTEST_TEST_CREDS
  static uint8_t ae[768];
  mtrc_tlv_writer w; mtrc_tlv_writer_init(&w, ae, sizeof(ae));
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(1), MTRC_CD, (size_t)MTRC_CD_LEN);  // certificationDeclaration
  mtrc_tlv_put_bytes(&w, mtrc_tlv_ctx(2), nonce, nlen);                   // attestationNonce
  mtrc_tlv_put_uint (&w, mtrc_tlv_ctx(3), 0);                             // timestamp
  mtrc_tlv_end_container(&w);
  if (!mtrc_tlv_writer_ok(&w)) return -1;
  size_t ael = mtrc_tlv_writer_len(&w);
  static uint8_t hin[768 + 16];
  memcpy(hin, ae, ael); memcpy(hin + ael, g.att, 16);
  uint8_t h[32]; mtrc_sha256(hin, ael + 16, h);
  uint8_t sig[64]; if (!mtrc_ecdsa_sign(sig, h, MTRC_DAC_PRIV)) return -1;
  return build_cmd_resp_bytes(out, cap, ep, cl, 0x01, ae, ael, sig, 64);
#else
  (void)out; (void)cap; (void)ep; (void)cl; (void)nonce; (void)nlen; return -1;
#endif
}

// Build a NOCResponse (NOC cluster cmd 0x08): {0:statusCode, 1:fabricIndex,
// 2:debugText}. statusCode 0 = OK (NodeOperationalCertStatusEnum).
static int build_noc_response(uint8_t *out, size_t cap, uint16_t ep, uint32_t cl,
                              uint8_t status, uint8_t fabric_index) {
  mtrc_tlv_writer w; mtrc_tlv_writer_init(&w, out, cap);
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());          // InvokeResponseMessage
  mtrc_tlv_put_bool(&w, mtrc_tlv_ctx(0), false);
  mtrc_tlv_start_array(&w, mtrc_tlv_ctx(1));           // InvokeResponses
  mtrc_tlv_start_struct(&w, mtrc_tlv_anon());          //  InvokeResponseIB
  mtrc_tlv_start_struct(&w, mtrc_tlv_ctx(0));          //   command CommandDataIB
  mtrc_tlv_start_list(&w, mtrc_tlv_ctx(0));            //    CommandPath
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0), ep);
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(1), cl);
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(2), 0x08);        //    NOCResponse
  mtrc_tlv_end_container(&w);
  mtrc_tlv_start_struct(&w, mtrc_tlv_ctx(1));          //    CommandFields
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0), status);      //     statusCode
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(1), fabric_index);//     fabricIndex
  mtrc_tlv_put_utf8(&w, mtrc_tlv_ctx(2), "", 0);       //     debugText ""
  mtrc_tlv_end_container(&w);                          //    end CommandFields
  mtrc_tlv_end_container(&w);                          //   end CommandDataIB
  mtrc_tlv_end_container(&w);                          //  end InvokeResponseIB
  mtrc_tlv_end_container(&w);                          // end InvokeResponses
  mtrc_tlv_put_uint(&w, mtrc_tlv_ctx(0xFF), 1);
  mtrc_tlv_end_container(&w);                          // end message
  return mtrc_tlv_writer_ok(&w) ? (int)mtrc_tlv_writer_len(&w) : -1;
}

// AddNOC: parse the NOC + IPK + admin args, install the fabric (CSR-generated
// operational key + the AddTrustedRootCertificate root) into mtrc_store, and
// build the NOCResponse. NOC chain verify is relaxed for now (A1b).
static int build_addnoc(uint8_t *out, size_t cap, uint16_t ep, uint32_t cl,
                        const uint8_t *payload, size_t plen) {
  const uint8_t *noc = NULL, *ipk = NULL; size_t noclen = 0, ipklen = 0;
  uint64_t admin_subj = 0, admin_vid = 0;
  if (!inv_field(payload, plen, 0, 1, &noc, &noclen, NULL))
    return build_noc_response(out, cap, ep, cl, 0x02, 0);   // InvalidNOC
  inv_field(payload, plen, 2, 1, &ipk, &ipklen, NULL);
  inv_field(payload, plen, 3, 0, NULL, NULL, &admin_subj);
  inv_field(payload, plen, 4, 0, NULL, NULL, &admin_vid);

  mtrc_cert nc;
  if (!mtrc_cert_parse(noc, noclen, &nc) || !nc.have_pubkey ||
      !g.have_pending_op || !g.have_pending_root)
    return build_noc_response(out, cap, ep, cl, 0x02, 0);   // InvalidNOC

  mtrc_fabric *f = mtrc_store_alloc();
  if (!f) return build_noc_response(out, cap, ep, cl, 0x05, 0);   // TableFull
  f->fabric_id = nc.have_fabric_id ? nc.subject_fabric_id : 0;
  f->node_id   = nc.have_node_id   ? nc.subject_node_id   : 0;
  f->admin_vendor_id = (uint16_t)admin_vid;
  memcpy(f->root_pub, g.pending_root_pub, 65);
  memset(f->ipk, 0, 16);
  if (ipk && ipklen <= 16) memcpy(f->ipk, ipk, ipklen);
  memcpy(f->op_priv, g.pending_op_priv, 32);
  memcpy(f->op_pub,  g.pending_op_pub, 65);
  if (noclen <= MTRC_NOC_MAX) { memcpy(f->noc, noc, noclen); f->noc_len = (uint16_t)noclen; }
  (void)admin_subj;

  char m[96];
  snprintf(m, sizeof(m), "NOC: fabric installed idx=%u fab=0x%08lX node=0x%08lX",
           (unsigned)f->fabric_index, (unsigned long)f->fabric_id,
           (unsigned long)f->node_id);
  mlog(MATTER_LOG_INFO, m);
  return build_noc_response(out, cap, ep, cl, 0x00, f->fabric_index);   // OK
}

// Handle a decrypted IM InvokeRequest. P3b.1 answers the General
// Commissioning commands ({errorCode, debugText}); anything else gets an
// UNSUPPORTED_COMMAND status.
static void im_handle_invoke(const uint8_t *payload, size_t plen,
                             uint16_t exch, uint32_t ack) {
  uint16_t ep; uint32_t cl, cmd;
  if (!mtrc_im_parse_first_command(payload, plen, &ep, &cl, &cmd)) return;
  char m[80];
  snprintf(m, sizeof(m), "IM Invoke ep=%u cluster=0x%04X cmd=0x%02X",
           (unsigned)ep, (unsigned)cl, (unsigned)cmd);
  mlog(MATTER_LOG_INFO, m);

  static uint8_t resp[1024];          // CSA DAC/PAI (~500B) + CD (~540B) responses
  int n = -1;
  if (cl == 0x003E && cmd == 0x02) {  // CertificateChainRequest -> Response(0x03)
#ifdef MTRC_ATTEST_TEST_CREDS
    uint64_t ct = 0;
    if (inv_field(payload, plen, 0, 0, NULL, NULL, &ct)) {
      if (ct == 1)
        n = build_cmd_resp_bytes(resp, sizeof(resp), ep, cl, 0x03, MTRC_DAC_DER, MTRC_DAC_DER_LEN, NULL, 0);
      else if (ct == 2)
        n = build_cmd_resp_bytes(resp, sizeof(resp), ep, cl, 0x03, MTRC_PAI_DER, MTRC_PAI_DER_LEN, NULL, 0);
    }
    if (n > 0) mlog(MATTER_LOG_INFO, "NOC: CertificateChainResponse sent");
#endif
  } else if (cl == 0x003E && cmd == 0x00) {   // AttestationRequest -> Response(0x01)
    const uint8_t *nonce = NULL; size_t nlen = 0;
    if (inv_field(payload, plen, 0, 1, &nonce, &nlen, NULL))
      n = build_attestation_response(resp, sizeof(resp), ep, cl, nonce, nlen);
    if (n > 0) mlog(MATTER_LOG_INFO, "NOC: AttestationResponse sent (DAC-signed)");
  } else if (cl == 0x003E && cmd == 0x04) {  // NOC: CSRRequest -> CSRResponse
    const uint8_t *nonce = NULL; size_t nlen = 0;
    if (inv_field(payload, plen, 0, 1, &nonce, &nlen, NULL))
      n = build_csr_response(resp, sizeof(resp), ep, cl, nonce, nlen);
    if (n > 0) mlog(MATTER_LOG_INFO, "NOC: CSRResponse sent (operational keypair + CSR)");
  } else if (cl == 0x003E && cmd == 0x0B) {   // AddTrustedRootCertificate
    const uint8_t *rc = NULL; size_t rcl = 0; mtrc_cert root;
    if (inv_field(payload, plen, 0, 1, &rc, &rcl, NULL) &&
        mtrc_cert_parse(rc, rcl, &root) && root.have_pubkey) {
      memcpy(g.pending_root_pub, root.pubkey, 65);
      g.have_pending_root = true;
      n = mtrc_im_build_status(resp, sizeof(resp), ep, cl, cmd, 0x00);   // SUCCESS
      mlog(MATTER_LOG_INFO, "NOC: trusted root stored");
    }
  } else if (cl == 0x003E && cmd == 0x06) {   // AddNOC -> NOCResponse
    n = build_addnoc(resp, sizeof(resp), ep, cl, payload, plen);
  } else if (cl == 0x0030) {          // General Commissioning (handled in-core)
    uint32_t rc = 0xFFFFFFFF;
    if      (cmd == 0x00) rc = 0x01;  // ArmFailSafe -> ArmFailSafeResponse
    else if (cmd == 0x02) rc = 0x03;  // SetRegulatoryConfig -> Response
    else if (cmd == 0x04) rc = 0x05;  // CommissioningComplete -> Response
    if (rc != 0xFFFFFFFF)
      n = mtrc_im_build_cmd_response_u8(resp, sizeof(resp), ep, cl, rc, 0); // errorCode OK
  } else if (cl == 0x0006 && cmd <= 0x02) {   // OnOff: Off(0)/On(1)/Toggle(2)
    // Route to the application (script's MatterInvoke -> relay, or the built-in
    // relay default). on_command owns the action; on_attr_write is the legacy
    // fallback for hosts that don't provide on_command.
    int handled = 0;
    if (g.port.on_command)
      handled = g.port.on_command(g.port.ctx, ep, cl, cmd, (int32_t)cmd);
    else if (g.port.on_attr_write) {
      uint8_t action = (uint8_t)cmd;          // maps 1:1 to Tasmota POWER_*
      g.port.on_attr_write(g.port.ctx, ep, 0x0006, 0x0000, &action, 1);
      handled = 1;
    }
    g.onoff = (cmd == 0x02) ? !g.onoff : (cmd == 0x01);
    mtrc_dm_set(ep, 0x0006, 0x0000, g.onoff ? 1 : 0);   // keep registry in sync
    if (handled)
      n = mtrc_im_build_status(resp, sizeof(resp), ep, cl, cmd, 0x00);  // SUCCESS
  } else if (g.port.on_command) {     // any other app cluster -> let a script try
    if (g.port.on_command(g.port.ctx, ep, cl, cmd, (int32_t)cmd))
      n = mtrc_im_build_status(resp, sizeof(resp), ep, cl, cmd, 0x00);  // SUCCESS
  }
  if (n < 0)
    n = mtrc_im_build_status(resp, sizeof(resp), ep, cl, cmd, 0x81); // UNSUPPORTED_COMMAND

  if (n > 0) {
    secured_send(MTRC_IM_INVOKE_RESPONSE, MTRC_PROTO_IM, resp, (size_t)n, exch, true, ack);
    mlog(MATTER_LOG_INFO, "IM InvokeResponse sent");
  }
}

// Build a Descriptor (0x001D) attribute report from the data-model registry:
//   0x0000 DeviceTypeList, 0x0001 ServerList, 0x0002 ClientList (empty),
//   0x0003 PartsList. Returns the encoded length, or -1.
static int build_descriptor_report(uint8_t *out, size_t cap, uint32_t sub_id,
                                   uint16_t ep, uint32_t attr) {
  if (attr == 0x0000) {                              // DeviceTypeList
    uint32_t dt = 0; mtrc_dm_endpoint_device_type(ep, &dt);
    return mtrc_im_build_report_devtypelist(out, cap, sub_id, ep, 0x001D, attr, dt, 1);
  }
  if (attr == 0x0001) {                              // ServerList (clusters on ep)
    uint32_t list[MTRC_DM_MAX_CLUSTERS]; int n = 0;
    for (int i = 0; i < mtrc_dm_cluster_count(); i++) {
      const mtrc_dm_cluster_t *c = mtrc_dm_cluster_at(i);
      if (c && c->endpoint == ep && n < (int)(sizeof(list)/sizeof(list[0])))
        list[n++] = c->cluster;
    }
    return mtrc_im_build_report_list_uint(out, cap, sub_id, ep, 0x001D, attr, list, n);
  }
  if (attr == 0x0003) {                              // PartsList (ep0: child eps)
    uint32_t list[MTRC_DM_MAX_ENDPOINTS]; int n = 0;
    if (ep == 0) {
      for (int i = 0; i < mtrc_dm_endpoint_count(); i++) {
        const mtrc_dm_endpoint_t *e = mtrc_dm_endpoint_at(i);
        if (e && e->endpoint != 0 && n < (int)(sizeof(list)/sizeof(list[0])))
          list[n++] = e->endpoint;
      }
    }
    return mtrc_im_build_report_list_uint(out, cap, sub_id, ep, 0x001D, attr, list, n);
  }
  return mtrc_im_build_report_list_uint(out, cap, sub_id, ep, 0x001D, attr, NULL, 0);
}

// Handle a decrypted IM ReadRequest: report the requested attribute. Descriptor
// (0x001D) lists come from the registry; OnOff (0x0006/0x0000 -> relay state)
// and Basic Information are scalars; everything else reports 0.
static void im_handle_read(const uint8_t *payload, size_t plen,
                           uint16_t exch, uint32_t ack) {
  uint16_t ep; uint32_t cl, attr;
  if (!mtrc_im_parse_first_attribute(payload, plen, &ep, &cl, &attr)) return;
  char m[80];
  snprintf(m, sizeof(m), "IM Read ep=%u cluster=0x%04X attr=0x%04X",
           (unsigned)ep, (unsigned)cl, (unsigned)attr);
  mlog(MATTER_LOG_INFO, m);

  static uint8_t resp[256];
  int n = (cl == 0x001D)
        ? build_descriptor_report(resp, sizeof(resp), 0, ep, attr)
        : mtrc_im_build_report_uint(resp, sizeof(resp), 0, ep, cl, attr,
                                    attr_value(ep, cl, attr));
  if (n > 0) {
    secured_send(MTRC_IM_REPORT_DATA, MTRC_PROTO_IM, resp, (size_t)n, exch, true, ack);
    mlog(MATTER_LOG_INFO, "IM ReportData sent");
  }
}

// Handle a SubscribeRequest: register a subscription, send a priming
// ReportData + SubscribeResponse. Periodic/changed reports come from
// matter_loop. (Single subscription supported.)
static void im_handle_subscribe(const uint8_t *payload, size_t plen,
                                uint16_t exch, uint32_t ack) {
  uint16_t ep, maxc; uint32_t cl, attr;
  if (!mtrc_im_parse_subscribe(payload, plen, &ep, &cl, &attr, &maxc)) return;
  g.sub_active = true;
  g.sub_id = (g.sub_id ? g.sub_id : 1) + 1;
  g.sub_ep = ep; g.sub_cl = cl; g.sub_attr = attr;
  g.sub_max_s = (maxc == 0 || maxc > 60) ? 30 : maxc;   // clamp
  g.sub_exch = exch;
  g.sub_last_val = attr_value(ep, cl, attr);
  g.sub_last_ms = g.port.millis(g.port.ctx);

  char m[80];
  snprintf(m, sizeof(m), "IM Subscribe ep=%u cl=0x%04X attr=0x%04X max=%us id=%u",
           (unsigned)ep,(unsigned)cl,(unsigned)attr,(unsigned)g.sub_max_s,(unsigned)g.sub_id);
  mlog(MATTER_LOG_INFO, m);

  static uint8_t rep[160];
  int n = mtrc_im_build_report_uint(rep, sizeof(rep), g.sub_id, ep, cl, attr, g.sub_last_val);
  if (n > 0) secured_send(MTRC_IM_REPORT_DATA, MTRC_PROTO_IM, rep, (size_t)n, exch, true, ack);
  n = mtrc_im_build_subscribe_response(rep, sizeof(rep), g.sub_id, g.sub_max_s);
  if (n > 0) secured_send(MTRC_IM_SUBSCRIBE_RESPONSE, MTRC_PROTO_IM, rep, (size_t)n, exch, false, 0);
  mlog(MATTER_LOG_INFO, "IM SubscribeResponse sent (priming report + subscribe)");
}

// A message arrived on the established PASE secure session: decrypt with the
// I2R key, parse the inner protocol header, dispatch the IM.
static void secured_dispatch(const uint8_t *buf, size_t len, const uint8_t *rx_key) {
  mtrc_msg_header mh; mtrc_proto_header ph;
  const uint8_t *ipl; size_t ipll;
  static uint8_t pt[1280];
  if (!mtrc_sec_decode(buf, len, rx_key, &mh, &ph, pt, sizeof(pt), &ipl, &ipll)) {
    mlog(MATTER_LOG_ERROR, "secured rx: MIC/decrypt failed");
    return;
  }
  if (ph.protocol_id == MTRC_PROTO_IM && ph.opcode == MTRC_IM_INVOKE_REQUEST) {
    im_handle_invoke(ipl, ipll, ph.exchange_id, mh.msg_counter);
  } else if (ph.protocol_id == MTRC_PROTO_IM && ph.opcode == MTRC_IM_READ_REQUEST) {
    im_handle_read(ipl, ipll, ph.exchange_id, mh.msg_counter);
  } else if (ph.protocol_id == MTRC_PROTO_IM && ph.opcode == MTRC_IM_SUBSCRIBE_REQUEST) {
    im_handle_subscribe(ipl, ipll, ph.exchange_id, mh.msg_counter);
  } else {
    char m[80];
    snprintf(m, sizeof(m), "secured rx proto=0x%04X op=0x%02X (unhandled)",
             (unsigned)ph.protocol_id, (unsigned)ph.opcode);
    mlog(MATTER_LOG_INFO, m);
  }
}

static void pase_dispatch(const uint8_t *buf, size_t len, uint16_t src_port) {
  (void)src_port;
  // Peek the message header to route by session id.
  mtrc_msg_header mh0;
  if (mtrc_frame_decode_msg_header(buf, len, &mh0) < 0) return;

  if (mh0.session_id != 0) {
    // Secured session traffic: PASE (commissioning IM) or CASE (operational).
    if (g.pase_secure && mh0.session_id == g.my_session_id) {
      tx_use_pase();
      secured_dispatch(buf, len, g.i2r);
    } else if (g.case_secure && mh0.session_id == g.case_my_sid) {
      tx_use_case();
      secured_dispatch(buf, len, g.case_i2r);
    }
    return;
  }

  // Unsecured session (id 0): PASE over Secure Channel.
  mtrc_msg_header mh; mtrc_proto_header ph;
  const uint8_t *pl; size_t pll;
  if (mtrc_frame_decode(buf, len, &mh, &ph, &pl, &pll) <= 0) return;
  if (ph.protocol_id != MTRC_PROTO_SECURE_CHANNEL) return;
  g.exchange_id = ph.exchange_id;
  switch (ph.opcode) {
    case MTRC_SC_PBKDF_PARAM_REQ: pase_handle_param_req(pl, pll, &mh); break;
    case MTRC_SC_PASE_PAKE1:      pase_handle_pake1(pl, pll, &mh);     break;
    case MTRC_SC_PASE_PAKE3:      pase_handle_pake3(pl, pll, &mh);     break;
    case MTRC_SC_CASE_SIGMA1:     case_handle_sigma1(pl, pll, &mh);    break;
    case MTRC_SC_CASE_SIGMA3:     case_handle_sigma3(pl, pll, &mh);    break;
    default: break;
  }
}

void matter_loop(void) {
  if (!g.inited || !g.started) return;
  if (g.rx_pending) {
    g.rx_pending = false;
    pase_dispatch(g.rx_buf, g.rx_len, g.rx_src_port);   // crypto-heavy work here
  }
  // Subscription report engine: send a ReportData when the value changed or
  // the max interval elapsed.
  if (g.sub_active && g.pase_secure) {
    uint32_t now = g.port.millis(g.port.ctx);
    uint64_t v = attr_value(g.sub_ep, g.sub_cl, g.sub_attr);
    if (v != g.sub_last_val || (now - g.sub_last_ms) >= (uint32_t)g.sub_max_s * 1000u) {
      g.sub_last_val = v; g.sub_last_ms = now;
      static uint8_t rep[160];
      int n = mtrc_im_build_report_uint(rep, sizeof(rep), g.sub_id,
                                        g.sub_ep, g.sub_cl, g.sub_attr, v);
      if (n > 0) {
        tx_use_pase();   // the subscription was established over PASE
        secured_send(MTRC_IM_REPORT_DATA, MTRC_PROTO_IM, rep, (size_t)n, g.sub_exch, false, 0);
      }
    }
  }
}

// ---- inbound transport pumps ------------------------------------------
// May run in a network task — only copy + flag; processing is in matter_loop.
void matter_udp_rx(const uint8_t src_ip6[16], uint16_t src_port,
                   const void *buf, size_t len) {
  (void)src_ip6;
  if (!g.inited || g.rx_pending) return;        // sequential; MRP retransmits
  if (len == 0 || len > sizeof(g.rx_buf)) return;
  memcpy(g.rx_buf, buf, len);
  g.rx_len = len; g.rx_src_port = src_port;
  g.rx_pending = true;
}

void matter_ble_rx(const void *buf, size_t len) {
  (void)buf; (void)len;
  // TODO Phase 3: BTP reassembly -> PASE/commissioning message handler.
}

// ---- endpoints / attributes -------------------------------------------
int matter_add_endpoint(uint32_t device_type_id) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  uint16_t ep = g.next_ep;
  if (mtrc_dm_add_endpoint(ep, device_type_id) < 0) return MATTER_ERR_NO_MEM;
  mtrc_dm_add_cluster(ep, MTRC_CL_DESCRIPTOR);   // mandatory on every endpoint
  dm_attach_device_type(ep, device_type_id);
  g.next_ep++;
  return (int)ep;
}

// Decode a leading TLV scalar (uint/bool) into a u64. Returns 1 on success.
static int tlv_scalar_u64(const uint8_t *tlv, size_t len, uint64_t *out) {
  mtrc_tlv_reader r; mtrc_tlv_reader_init(&r, tlv, len);
  mtrc_tlv_elem e;
  if (!mtrc_tlv_read(&r, &e)) return 0;
  if (e.type == MTRC_TLV_UINT) { *out = e.u; return 1; }
  if (e.type == MTRC_TLV_BOOL) { *out = e.u ? 1 : 0; return 1; }
  return 0;
}

matter_err_t matter_set_attr(uint16_t endpoint, uint32_t cluster,
                             uint32_t attr, const uint8_t *tlv, size_t tlv_len) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  if (!tlv || tlv_len == 0) return MATTER_ERR_INVALID_ARG;
  uint64_t v;
  if (!tlv_scalar_u64(tlv, tlv_len, &v)) return MATTER_ERR_INVALID_ARG;
  // Auto-register the attribute if the host pushes a value before declaring it.
  if (!mtrc_dm_find(endpoint, cluster, attr))
    mtrc_dm_add_attr(endpoint, cluster, attr, MTRC_DM_T_U32, 0, v);
  else
    mtrc_dm_set(endpoint, cluster, attr, v);
  // The subscription report engine in matter_loop() picks up the change on the
  // next pump (it polls attr_value), so no immediate report is needed here.
  return MATTER_OK;
}

// ---- TinyC / script data-model bridge (Phase C2) -----------------------
void matter_reset_model(void) {
  if (!g.inited) return;
  mtrc_dm_reset();
  dm_seed_root();
  g.next_ep = 1;
}

matter_err_t matter_add_cluster(uint16_t endpoint, uint32_t cluster) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  return mtrc_dm_add_cluster(endpoint, cluster) == 0 ? MATTER_OK : MATTER_ERR_NO_MEM;
}

matter_err_t matter_add_attr(uint16_t endpoint, uint32_t cluster, uint32_t attr,
                             int type, int writable) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  if (type < 0 || type > MTRC_DM_T_ENUM8) type = MTRC_DM_T_U32;
  uint8_t flags = writable ? MTRC_DM_F_WRITABLE : 0;
  return mtrc_dm_add_attr(endpoint, cluster, attr, (mtrc_dm_type_t)type, flags, 0) == 0
         ? MATTER_OK : MATTER_ERR_NO_MEM;
}

matter_err_t matter_set_attr_uint(uint16_t endpoint, uint32_t cluster,
                                  uint32_t attr, uint64_t value) {
  if (!g.inited) return MATTER_ERR_NOT_INIT;
  if (!mtrc_dm_find(endpoint, cluster, attr))
    mtrc_dm_add_attr(endpoint, cluster, attr, MTRC_DM_T_U32, 0, value);
  else
    mtrc_dm_set(endpoint, cluster, attr, value);
  return MATTER_OK;
}

int matter_get_attr_uint(uint16_t endpoint, uint32_t cluster,
                         uint32_t attr, uint64_t *out) {
  if (!g.inited) return 0;
  return mtrc_dm_get(endpoint, cluster, attr, out);
}

// ---- onboarding + introspection ---------------------------------------
const char *matter_qr_uri(void)      { return g.qr; }      // "" until Phase 6
const char *matter_manual_code(void) { return g.manual; }  // "" until Phase 6
const char *matter_version(void)     { return MATTER_C_VERSION_STR; }
bool        matter_is_commissioned(void) { return false; } // TODO Phase 3
