#include "be_constobj.h"

static be_define_const_map_slots(be_class_tasmota_map) {
    { be_const_key(get_power, -1), be_const_func(l_getpower) },
    { be_const_key(locale, -1), be_const_func(l_locale) },
    { be_const_key(fast_loop, 23), be_const_closure(class_Tasmota_fast_loop_closure) },
    { be_const_key(exec_rules, -1), be_const_closure(class_Tasmota_exec_rules_closure) },
    { be_const_key(gen_cb, -1), be_const_closure(class_Tasmota_gen_cb_closure) },
    { be_const_key(get_light, 10), be_const_closure(class_Tasmota_get_light_closure) },
    { be_const_key(init, -1), be_const_closure(class_Tasmota_init_closure) },
    { be_const_key(_rules, 96), be_const_var(1) },
    { be_const_key(strptime, -1), be_const_func(l_strptime) },
    { be_const_key(_cmd, -1), be_const_func(l_cmd) },
    { be_const_key(try_rule, 83), be_const_closure(class_Tasmota_try_rule_closure) },
    { be_const_key(urlfetch, -1), be_const_closure(class_Tasmota_urlfetch_closure) },
    { be_const_key(resolvecmnd, 30), be_const_func(l_resolveCmnd) },
    { be_const_key(web_send, -1), be_const_func(l_webSend) },
    { be_const_key(time_dump, -1), be_const_func(l_time_dump) },
    { be_const_key(is_network_up, 54), be_const_closure(class_Tasmota_is_network_up_closure) },
    { be_const_key(hostname, -1), be_const_func(l_hostname) },
    { be_const_key(gc, -1), be_const_closure(class_Tasmota_gc_closure) },
    { be_const_key(delay_microseconds, -1), be_const_func(l_delay_microseconds) },
    { be_const_key(_wnu, -1), be_const_var(8) },
    { be_const_key(urlfetch_cmd, -1), be_const_closure(class_Tasmota_urlfetch_cmd_closure) },
    { be_const_key(publish_rule, -1), be_const_func(l_publish_rule) },
    { be_const_key(cmd_res, -1), be_const_var(11) },
    { be_const_key(set_light, 26), be_const_closure(class_Tasmota_set_light_closure) },
    { be_const_key(event, -1), be_const_closure(class_Tasmota_event_closure) },
    { be_const_key(_settings_def, -1), be_const_comptr(&be_tasmota_settings_struct) },
    { be_const_key(remove_fast_loop, -1), be_const_closure(class_Tasmota_remove_fast_loop_closure) },
    { be_const_key(read_sensors, 64), be_const_func(l_read_sensors) },
    { be_const_key(find_list_i, -1), be_const_closure(class_Tasmota_find_list_i_closure) },
    { be_const_key(get_switches, -1), be_const_func(l_getswitch) },
    { be_const_key(add_cron, -1), be_const_closure(class_Tasmota_add_cron_closure) },
    { be_const_key(set_timer, 29), be_const_closure(class_Tasmota_set_timer_closure) },
    { be_const_key(loglevel, -1), be_const_func(l_loglevel) },
    { be_const_key(response_append, -1), be_const_func(l_respAppend) },
    { be_const_key(remove_driver, -1), be_const_closure(class_Tasmota_remove_driver_closure) },
    { be_const_key(get_option, 68), be_const_func(l_getoption) },
    { be_const_key(_ccmd, -1), be_const_var(5) },
    { be_const_key(rtc, -1), be_const_static_func(l_rtc) },
    { be_const_key(find_key_i, 84), be_const_closure(class_Tasmota_find_key_i_closure) },
    { be_const_key(millis, -1), be_const_static_func(l_millis) },
    { be_const_key(Rule_Matcher, -1), be_const_class(be_class_Rule_Matcher) },
    { be_const_key(_ext, 69), be_const_var(7) },
    { be_const_key(publish_result, 70), be_const_func(l_publish_result) },
    { be_const_key(time_reached, 107), be_const_func(l_timereached) },
    { be_const_key(remove_cron, -1), be_const_closure(class_Tasmota_remove_cron_closure) },
    { be_const_key(next_cron, -1), be_const_closure(class_Tasmota_next_cron_closure) },
    { be_const_key(webcolor, 71), be_const_static_func(l_webcolor) },
    { be_const_key(wire_scan, 8), be_const_closure(class_Tasmota_wire_scan_closure) },
    { be_const_key(delay, -1), be_const_func(l_delay) },
    { be_const_key(find_op, 73), be_const_closure(class_Tasmota_find_op_closure) },
    { be_const_key(yield, 15), be_const_func(l_yield) },
    { be_const_key(cmd, -1), be_const_closure(class_Tasmota_cmd_closure) },
    { be_const_key(_settings_ptr, -1), be_const_comptr(&Settings) },
    { be_const_key(_crons, -1), be_const_var(4) },
    { be_const_key(wire1, -1), be_const_var(9) },
    { be_const_key(_apply_str_op, -1), be_const_func(tasm_apply_str_op) },
    { be_const_key(strftime, 62), be_const_func(l_strftime) },
    { be_const_key(resp_cmnd, -1), be_const_func(l_respCmnd) },
    { be_const_key(_defer, -1), be_const_var(3) },
    { be_const_key(resp_cmnd_done, -1), be_const_func(l_respCmndDone) },
    { be_const_key(compile, -1), be_const_closure(class_Tasmota_compile_closure) },
    { be_const_key(add_fast_loop, 37), be_const_closure(class_Tasmota_add_fast_loop_closure) },
    { be_const_key(resp_cmnd_str, -1), be_const_func(l_respCmndStr) },
    { be_const_key(log, -1), be_const_func(l_logInfo) },
    { be_const_key(hs2rgb, 18), be_const_closure(class_Tasmota_hs2rgb_closure) },
    { be_const_key(get_free_heap, -1), be_const_func(l_getFreeHeap) },
    { be_const_key(arch, 56), be_const_static_func(l_arch) },
    { be_const_key(_find_op, -1), be_const_func(tasm_find_op) },
    { be_const_key(scale_int, -1), be_const_static_func(l_scaleint) },
    { be_const_key(resp_cmnd_failed, -1), be_const_func(l_respCmndFailed) },
    { be_const_key(_global_def, -1), be_const_comptr(&be_tasmota_global_struct) },
    { be_const_key(micros, 112), be_const_static_func(l_micros) },
    { be_const_key(check_not_method, 4), be_const_closure(class_Tasmota_check_not_method_closure) },
    { be_const_key(remove_timer, 44), be_const_closure(class_Tasmota_remove_timer_closure) },
    { be_const_key(int, -1), be_const_static_closure(class_Tasmota_int_closure) },
    { be_const_key(web_send_decimal, -1), be_const_func(l_webSendDecimal) },
    { be_const_key(load, -1), be_const_closure(class_Tasmota_load_closure) },
    { be_const_key(exec_tele, -1), be_const_closure(class_Tasmota_exec_tele_closure) },
    { be_const_key(run_cron, 95), be_const_closure(class_Tasmota_run_cron_closure) },
    { be_const_key(run_timers, -1), be_const_closure(class_Tasmota_run_timers_closure) },
    { be_const_key(_fl, -1), be_const_var(0) },
    { be_const_key(read_extension_manifest, -1), be_const_closure(class_Tasmota_read_extension_manifest_closure) },
    { be_const_key(_drivers, -1), be_const_var(6) },
    { be_const_key(run_deferred, -1), be_const_closure(class_Tasmota_run_deferred_closure) },
    { be_const_key(unload_extension, -1), be_const_closure(class_Tasmota_unload_extension_closure) },
    { be_const_key(_global_addr, -1), be_const_comptr(&TasmotaGlobal) },
    { be_const_key(get_switch, 43), be_const_func(l_getswitch) },
    { be_const_key(_debug_present, 35), be_const_var(15) },
    { be_const_key(_timers, -1), be_const_var(2) },
    { be_const_key(remove_rule, -1), be_const_closure(class_Tasmota_remove_rule_closure) },
    { be_const_key(rtc_utc, 41), be_const_func(l_rtc_utc) },
    { be_const_key(exec_cmd, 47), be_const_closure(class_Tasmota_exec_cmd_closure) },
    { be_const_key(add_rule, -1), be_const_closure(class_Tasmota_add_rule_closure) },
    { be_const_key(memory, 59), be_const_static_func(l_memory) },
    { be_const_key(when_network_up, -1), be_const_closure(class_Tasmota_when_network_up_closure) },
    { be_const_key(scale_uint, -1), be_const_static_func(l_scaleuint) },
    { be_const_key(defer, 105), be_const_closure(class_Tasmota_defer_closure) },
    { be_const_key(run_network_up, 92), be_const_closure(class_Tasmota_run_network_up_closure) },
    { be_const_key(add_driver, 78), be_const_closure(class_Tasmota_add_driver_closure) },
    { be_const_key(add_extension, -1), be_const_closure(class_Tasmota_add_extension_closure) },
    { be_const_key(add_cmd, -1), be_const_closure(class_Tasmota_add_cmd_closure) },
    { be_const_key(add_rule_once, 38), be_const_closure(class_Tasmota_add_rule_once_closure) },
    { be_const_key(set_power, -1), be_const_func(l_setpower) },
    { be_const_key(wire2, -1), be_const_var(10) },
    { be_const_key(sine_int, -1), be_const_static_func(l_sineint) },
    { be_const_key(remove_cmd, 109), be_const_closure(class_Tasmota_remove_cmd_closure) },
    { be_const_key(settings, -1), be_const_var(13) },
    { be_const_key(global, -1), be_const_var(12) },
    { be_const_key(save, -1), be_const_func(l_save) },
    { be_const_key(version, 114), be_const_ctype_func(be_Tasmota_version) },
    { be_const_key(time_str, -1), be_const_closure(class_Tasmota_time_str_closure) },
    { be_const_key(wifi, 57), be_const_static_func(l_wifi) },
    { be_const_key(wd, -1), be_const_var(14) },
    { be_const_key(i2c_enabled, 116), be_const_func(l_i2cenabled) },
    { be_const_key(resp_cmnd_error, -1), be_const_func(l_respCmndError) },
    { be_const_key(eth, -1), be_const_static_func(l_eth) },
    { be_const_key(publish, -1), be_const_func(be_mqtt_publish) },
};

static be_define_const_map(
    be_class_tasmota_map,
    117
);

BE_EXPORT_VARIABLE be_define_const_class(
    be_class_tasmota,
    16,
    NULL,
    Tasmota
);
