#include "be_constobj.h"

static be_define_const_map_slots(m_libmatter_map) {
    { be_const_key_weak(DAC_Pub_FFF1_8000, 5), be_const_func(matter_DAC_Pub_FFF1_8000) },
    { be_const_key_weak(ReportDataMessage, -1), be_const_class(be_class_Matter_ReportDataMessage) },
    { be_const_key_weak(Fabric, 50), be_const_class(be_class_Matter_Fabric) },
    { be_const_key_weak(UNSUPPORTED_NODE, -1), be_const_int(0x9B) },
    { be_const_key_weak(MATTER_OPTION, -1), be_const_int(151) },
    { be_const_key_weak(HTTP_remote, 79), be_const_class(be_class_Matter_HTTP_remote) },
    { be_const_key_weak(Path, -1), be_const_class(be_class_Matter_Path) },
    { be_const_key_weak(Base38, 56), be_const_class(be_class_Matter_Base38) },
    { be_const_key_weak(UI, -1), be_const_class(be_class_Matter_UI) },
    { be_const_key_weak(PathGenerator, 134), be_const_class(be_class_Matter_PathGenerator) },
    { be_const_key_weak(IM_SubscribedHeartbeat, -1), be_const_class(be_class_Matter_IM_SubscribedHeartbeat) },
    { be_const_key_weak(AttributePathIB, -1), be_const_class(be_class_Matter_AttributePathIB) },
    { be_const_key_weak(IM_SubscribeResponse_Pull, 136), be_const_class(be_class_Matter_IM_SubscribeResponse_Pull) },
    { be_const_key_weak(Sigma3, -1), be_const_class(be_class_Matter_Sigma3) },
    { be_const_key_weak(SubscribeRequestMessage, -1), be_const_class(be_class_Matter_SubscribeRequestMessage) },
    { be_const_key_weak(Sigma2Resume, -1), be_const_class(be_class_Matter_Sigma2Resume) },
    { be_const_key_weak(Expirable_list, -1), be_const_class(be_class_Matter_Expirable_list) },
    { be_const_key_weak(FAILURE, -1), be_const_int(0x01) },
    { be_const_key_weak(INVALID_DATA_TYPE, -1), be_const_int(0x8D) },
    { be_const_key_weak(DATA_VERSION_MISMATCH, 121), be_const_int(0x92) },
    { be_const_key_weak(EventGenerator, 70), be_const_class(be_class_Matter_EventGenerator) },
    { be_const_key_weak(get_command_name, 114), be_const_ctype_func(matter_get_command_name) },
    { be_const_key_weak(IM_Status, -1), be_const_class(be_class_Matter_IM_Status) },
    { be_const_key_weak(InvokeResponseMessage, -1), be_const_class(be_class_Matter_InvokeResponseMessage) },
    { be_const_key_weak(setmember, -1), be_const_closure(module_matter_setmember_closure) },
    { be_const_key_weak(SubscribeResponseMessage, 47), be_const_class(be_class_Matter_SubscribeResponseMessage) },
    { be_const_key_weak(RESOURCE_EXHAUSTED, 17), be_const_int(0x89) },
    { be_const_key_weak(UNREPORTABLE_ATTRIBUTE, -1), be_const_int(0x8C) },
    { be_const_key_weak(PBKDFParamRequest, 1), be_const_class(be_class_Matter_PBKDFParamRequest) },
    { be_const_key_weak(ReadRequestMessage_solo, 12), be_const_class(be_class_Matter_ReadRequestMessage_solo) },
    { be_const_key_weak(MessageHandler, -1), be_const_class(be_class_Matter_MessageHandler) },
    { be_const_key_weak(CommandDataIB, 52), be_const_class(be_class_Matter_CommandDataIB) },
    { be_const_key_weak(INVALID_SUBSCRIPTION, -1), be_const_int(0x7D) },
    { be_const_key_weak(Expirable, -1), be_const_class(be_class_Matter_Expirable) },
    { be_const_key_weak(AGGREGATOR_ENDPOINT, -1), be_const_int(0x0001) },
    { be_const_key_weak(PAI_Pub_FFF1, 26), be_const_func(matter_PAI_Pub_FFF1) },
    { be_const_key_weak(FAILSAFE_REQUIRED, -1), be_const_int(0xCA) },
    { be_const_key_weak(UDPPacket_sent, -1), be_const_class(be_class_Matter_UDPPacket_sent) },
    { be_const_key_weak(Sigma2, -1), be_const_class(be_class_Matter_Sigma2) },
    { be_const_key_weak(sort, -1), be_const_closure(module_matter_sort_closure) },
    { be_const_key_weak(HTTP_async, -1), be_const_class(be_class_Matter_HTTP_async) },
    { be_const_key_weak(UNSUPPORTED_EVENT, -1), be_const_int(0xC7) },
    { be_const_key_weak(TimedRequestMessage, -1), be_const_class(be_class_Matter_TimedRequestMessage) },
    { be_const_key_weak(INVALID_ACTION, -1), be_const_int(0x80) },
    { be_const_key_weak(DataVersionFilterIB, -1), be_const_class(be_class_Matter_DataVersionFilterIB) },
    { be_const_key_weak(Sigma1, -1), be_const_class(be_class_Matter_Sigma1) },
    { be_const_key_weak(PBKDFParamResponse, -1), be_const_class(be_class_Matter_PBKDFParamResponse) },
    { be_const_key_weak(IM_InvokeResponse, -1), be_const_class(be_class_Matter_IM_InvokeResponse) },
    { be_const_key_weak(NO_UPSTREAM_SUBSCRIP_XADTION, -1), be_const_int(0xC5) },
    { be_const_key_weak(Plugin_Root, 3), be_const_class(be_class_Matter_Plugin_Root) },
    { be_const_key_weak(get_event_name, -1), be_const_ctype_func(matter_get_event_name) },
    { be_const_key_weak(UNSUPPORTED_CLUSTER, -1), be_const_int(0xC3) },
    { be_const_key_weak(jitter, 90), be_const_closure(module_matter_jitter_closure) },
    { be_const_key_weak(is_attribute_reportable, -1), be_const_ctype_func(matter_is_attribute_reportable) },
    { be_const_key_weak(publish_command, -1), be_const_func(matter_publish_command) },
    { be_const_key_weak(IM_Subscription, 91), be_const_class(be_class_Matter_IM_Subscription) },
    { be_const_key_weak(InvokeRequestMessage_solo, 120), be_const_class(be_class_Matter_InvokeRequestMessage_solo) },
    { be_const_key_weak(ClusterPathIB, -1), be_const_class(be_class_Matter_ClusterPathIB) },
    { be_const_key_weak(PAI_Cert_FFF1, 18), be_const_func(matter_PAI_Cert_FFF1) },
    { be_const_key_weak(NOT_FOUND, -1), be_const_int(0x8B) },
    { be_const_key_weak(PATHS_EXHAUSTED, 88), be_const_int(0xC8) },
    { be_const_key_weak(_ADD_ENDPOINT_JS, 48), be_const_comptr(MATTER_ADD_ENDPOINT_HINTS_JS) },
    { be_const_key_weak(UNSUPPORTED_WRITE, 36), be_const_int(0x88) },
    { be_const_key_weak(WriteResponseMessage, 77), be_const_class(be_class_Matter_WriteResponseMessage) },
    { be_const_key_weak(EventFilterIB, -1), be_const_class(be_class_Matter_EventFilterIB) },
    { be_const_key_weak(Session_Store, -1), be_const_class(be_class_Matter_Session_Store) },
    { be_const_key_weak(Profiler, -1), be_const_class(be_class_Matter_Profiler) },
    { be_const_key_weak(ReadRequestMessage, 11), be_const_class(be_class_Matter_ReadRequestMessage) },
    { be_const_key_weak(get_vendor_name, -1), be_const_ctype_func(matter_get_vendor_name) },
    { be_const_key_weak(Pake3, -1), be_const_class(be_class_Matter_Pake3) },
    { be_const_key_weak(get_cluster_name, -1), be_const_ctype_func(matter_get_cluster_name) },
    { be_const_key_weak(inspect, -1), be_const_closure(module_matter_inspect_closure) },
    { be_const_key_weak(TIMEOUT, -1), be_const_int(0x94) },
    { be_const_key_weak(DAC_Cert_FFF1_8000, -1), be_const_func(matter_DAC_Cert_FFF1_8000) },
    { be_const_key_weak(consolidate_clusters, -1), be_const_closure(module_matter_consolidate_clusters_closure) },
    { be_const_key_weak(get_attribute_name, -1), be_const_ctype_func(matter_get_attribute_name) },
    { be_const_key_weak(Pake2, -1), be_const_class(be_class_Matter_Pake2) },
    { be_const_key_weak(EventStatusIB, 123), be_const_class(be_class_Matter_EventStatusIB) },
    { be_const_key_weak(Control_Message, -1), be_const_class(be_class_Matter_Control_Message) },
    { be_const_key_weak(EventDataIB, -1), be_const_class(be_class_Matter_EventDataIB) },
    { be_const_key_weak(IM_Subscription_Shop, -1), be_const_class(be_class_Matter_IM_Subscription_Shop) },
    { be_const_key_weak(AttributeStatusIB, 87), be_const_class(be_class_Matter_AttributeStatusIB) },
    { be_const_key_weak(EventReportIB, -1), be_const_class(be_class_Matter_EventReportIB) },
    { be_const_key_weak(UNSUPPORTED_ATTRIBUTE, -1), be_const_int(0x86) },
    { be_const_key_weak(AttributeDataIB, -1), be_const_class(be_class_Matter_AttributeDataIB) },
    { be_const_key_weak(START_ENDPOINT, 14), be_const_int(0x0002) },
    { be_const_key_weak(_STYLESHEET, -1), be_const_comptr(MATTER_STYLESHEET) },
    { be_const_key_weak(Verhoeff, -1), be_const_class(be_class_Matter_Verhoeff) },
    { be_const_key_weak(member, -1), be_const_closure(module_matter_member_closure) },
    { be_const_key_weak(EVENT_CRITICAL, 108), be_const_int(2) },
    { be_const_key_weak(Commisioning_Context, 13), be_const_class(be_class_Matter_Commisioning_Context) },
    { be_const_key_weak(Pake1, 115), be_const_class(be_class_Matter_Pake1) },
    { be_const_key_weak(UNSUPPORTED_ENDPOINT, -1), be_const_int(0x7F) },
    { be_const_key_weak(NEEDS_TIMED_INTERACTION, 25), be_const_int(0xC6) },
    { be_const_key_weak(DAC_Priv_FFF1_8000, 113), be_const_func(matter_DAC_Priv_FFF1_8000) },
    { be_const_key_weak(QRCode, 126), be_const_class(be_class_Matter_QRCode) },
    { be_const_key_weak(SUCCESS, -1), be_const_int(0x00) },
    { be_const_key_weak(UDPServer, -1), be_const_class(be_class_Matter_UDPServer) },
    { be_const_key_weak(StatusIB, 105), be_const_class(be_class_Matter_StatusIB) },
    { be_const_key_weak(UNSUPPORTED_ACCESS, -1), be_const_int(0x7E) },
    { be_const_key_weak(AttributeReportIB, 30), be_const_class(be_class_Matter_AttributeReportIB) },
    { be_const_key_weak(EventPathIB, -1), be_const_class(be_class_Matter_EventPathIB) },
    { be_const_key_weak(WriteRequestMessage, 75), be_const_class(be_class_Matter_WriteRequestMessage) },
    { be_const_key_weak(UNSUPPORTED_READ, 24), be_const_int(0x8F) },
    { be_const_key_weak(IM_WriteResponse, 81), be_const_class(be_class_Matter_IM_WriteResponse) },
    { be_const_key_weak(EVENT_INFO, -1), be_const_int(1) },
    { be_const_key_weak(BUSY, -1), be_const_int(0x9C) },
    { be_const_key_weak(StatusResponseMessage, -1), be_const_class(be_class_Matter_StatusResponseMessage) },
    { be_const_key_weak(EventHandler, -1), be_const_class(be_class_Matter_EventHandler) },
    { be_const_key_weak(EVENT_DEBUG, 60), be_const_int(0) },
    { be_const_key_weak(seconds_to_dhm, -1), be_const_ctype_func(matter_seconds_to_dhm) },
    { be_const_key_weak(Counter, -1), be_const_class(be_class_Matter_Counter) },
    { be_const_key_weak(IM_ReportData_Pull, -1), be_const_class(be_class_Matter_IM_ReportData_Pull) },
    { be_const_key_weak(UC_LIST, -1), be_const_closure(module_matter_UC_LIST_closure) },
    { be_const_key_weak(Session, -1), be_const_class(be_class_Matter_Session) },
    { be_const_key_weak(Plugin_Device, 9), be_const_class(be_class_Matter_Plugin_Device) },
    { be_const_key_weak(get_opcode_name, 63), be_const_ctype_func(matter_get_opcode_name) },
    { be_const_key_weak(get_ip_bytes, 65), be_const_ctype_func(matter_get_ip_bytes) },
    { be_const_key_weak(INVALID_COMMAND, -1), be_const_int(0x85) },
    { be_const_key_weak(CONSTRAINT_ERROR, -1), be_const_int(0x87) },
    { be_const_key_weak(TLV, -1), be_const_class(be_class_Matter_TLV) },
    { be_const_key_weak(IM, -1), be_const_class(be_class_Matter_IM) },
    { be_const_key_weak(Frame, 128), be_const_class(be_class_Matter_Frame) },
    { be_const_key_weak(Plugin_Aggregator, -1), be_const_class(be_class_Matter_Plugin_Aggregator) },
    { be_const_key_weak(CommandPathIB, 4), be_const_class(be_class_Matter_CommandPathIB) },
    { be_const_key_weak(is_attribute_writable, -1), be_const_ctype_func(matter_is_attribute_writable) },
    { be_const_key_weak(TIMED_REQUEST_MISMATCH, -1), be_const_int(0xC9) },
    { be_const_key_weak(PAI_Priv_FFF1, -1), be_const_func(matter_PAI_Priv_FFF1) },
    { be_const_key_weak(EventQueued, -1), be_const_class(be_class_Matter_EventQueued) },
    { be_const_key_weak(Device, 8), be_const_class(be_class_Matter_Device) },
    { be_const_key_weak(UNSUPPORTED_COMMAND, -1), be_const_int(0x81) },
    { be_const_key_weak(InvokeResponseIB, -1), be_const_class(be_class_Matter_InvokeResponseIB) },
    { be_const_key_weak(IM_ReportDataSubscribed_Pull, -1), be_const_class(be_class_Matter_IM_ReportDataSubscribed_Pull) },
    { be_const_key_weak(InvokeRequestMessage, -1), be_const_class(be_class_Matter_InvokeRequestMessage) },
    { be_const_key_weak(TCP_async, -1), be_const_class(be_class_Matter_TCP_async) },
    { be_const_key_weak(CommandStatusIB, -1), be_const_class(be_class_Matter_CommandStatusIB) },
    { be_const_key_weak(_LOGO, -1), be_const_comptr(MATTER_LOGO) },
    { be_const_key_weak(CD_FFF1_8000, -1), be_const_func(matter_CD_FFF1_8000) },
};

static be_define_const_map(
    m_libmatter_map,
    138
);

static be_define_const_module(
    m_libmatter,
    "matter"
);

BE_EXPORT_VARIABLE be_define_const_native_module(matter);
