// GENERATED by tools/gen_picotts.py - do not edit.
// Every string literal of the amalgamated engine. A plugin has no .rodata of its own, so the
// texts live in this blob, are copied word by word into the MODULE_MEMORY at pFUNC_INIT and
// PICO_S(n) points into that copy.
#ifndef PICOTTS_PLUGIN_STRINGS_H
#define PICOTTS_PLUGIN_STRINGS_H

#define PICO_STR_COUNT 161
#define PICO_STR_WORDS 642   // 2568 bytes
#define PICO_SOFF(n) (pico_soff_##n)
#define pico_soff_0 0
#define pico_soff_1 28
#define pico_soff_2 54
#define pico_soff_3 57
#define pico_soff_4 69
#define pico_soff_5 105
#define pico_soff_6 139
#define pico_soff_7 175
#define pico_soff_8 198
#define pico_soff_9 218
#define pico_soff_10 243
#define pico_soff_11 246
#define pico_soff_12 253
#define pico_soff_13 271
#define pico_soff_14 296
#define pico_soff_15 306
#define pico_soff_16 340
#define pico_soff_17 364
#define pico_soff_18 389
#define pico_soff_19 399
#define pico_soff_20 454
#define pico_soff_21 476
#define pico_soff_22 482
#define pico_soff_23 519
#define pico_soff_24 544
#define pico_soff_25 575
#define pico_soff_26 605
#define pico_soff_27 636
#define pico_soff_28 637
#define pico_soff_29 665
#define pico_soff_30 671
#define pico_soff_31 681
#define pico_soff_32 687
#define pico_soff_33 691
#define pico_soff_34 695
#define pico_soff_35 701
#define pico_soff_36 707
#define pico_soff_37 712
#define pico_soff_38 721
#define pico_soff_39 731
#define pico_soff_40 741
#define pico_soff_41 750
#define pico_soff_42 761
#define pico_soff_43 769
#define pico_soff_44 784
#define pico_soff_45 794
#define pico_soff_46 802
#define pico_soff_47 816
#define pico_soff_48 819
#define pico_soff_49 837
#define pico_soff_50 842
#define pico_soff_51 847
#define pico_soff_52 852
#define pico_soff_53 857
#define pico_soff_54 862
#define pico_soff_55 890
#define pico_soff_56 912
#define pico_soff_57 935
#define pico_soff_58 966
#define pico_soff_59 980
#define pico_soff_60 1000
#define pico_soff_61 1016
#define pico_soff_62 1030
#define pico_soff_63 1045
#define pico_soff_64 1058
#define pico_soff_65 1074
#define pico_soff_66 1091
#define pico_soff_67 1104
#define pico_soff_68 1118
#define pico_soff_69 1135
#define pico_soff_70 1156
#define pico_soff_71 1169
#define pico_soff_72 1184
#define pico_soff_73 1201
#define pico_soff_74 1222
#define pico_soff_75 1245
#define pico_soff_76 1262
#define pico_soff_77 1283
#define pico_soff_78 1309
#define pico_soff_79 1328
#define pico_soff_80 1340
#define pico_soff_81 1365
#define pico_soff_82 1383
#define pico_soff_83 1399
#define pico_soff_84 1413
#define pico_soff_85 1440
#define pico_soff_86 1464
#define pico_soff_87 1493
#define pico_soff_88 1515
#define pico_soff_89 1544
#define pico_soff_90 1578
#define pico_soff_91 1612
#define pico_soff_92 1618
#define pico_soff_93 1643
#define pico_soff_94 1677
#define pico_soff_95 1736
#define pico_soff_96 1738
#define pico_soff_97 1794
#define pico_soff_98 1796
#define pico_soff_99 1801
#define pico_soff_100 1804
#define pico_soff_101 1812
#define pico_soff_102 1819
#define pico_soff_103 1826
#define pico_soff_104 1843
#define pico_soff_105 1850
#define pico_soff_106 1852
#define pico_soff_107 1855
#define pico_soff_108 1861
#define pico_soff_109 1900
#define pico_soff_110 1922
#define pico_soff_111 1928
#define pico_soff_112 1950
#define pico_soff_113 1956
#define pico_soff_114 1979
#define pico_soff_115 1986
#define pico_soff_116 2010
#define pico_soff_117 2018
#define pico_soff_118 2023
#define pico_soff_119 2080
#define pico_soff_120 2140
#define pico_soff_121 2180
#define pico_soff_122 2200
#define pico_soff_123 2240
#define pico_soff_124 2274
#define pico_soff_125 2276
#define pico_soff_126 2303
#define pico_soff_127 2308
#define pico_soff_128 2315
#define pico_soff_129 2321
#define pico_soff_130 2336
#define pico_soff_131 2341
#define pico_soff_132 2346
#define pico_soff_133 2353
#define pico_soff_134 2361
#define pico_soff_135 2370
#define pico_soff_136 2380
#define pico_soff_137 2382
#define pico_soff_138 2388
#define pico_soff_139 2394
#define pico_soff_140 2402
#define pico_soff_141 2407
#define pico_soff_142 2413
#define pico_soff_143 2418
#define pico_soff_144 2432
#define pico_soff_145 2437
#define pico_soff_146 2440
#define pico_soff_147 2443
#define pico_soff_148 2448
#define pico_soff_149 2453
#define pico_soff_150 2459
#define pico_soff_151 2465
#define pico_soff_152 2474
#define pico_soff_153 2483
#define pico_soff_154 2492
#define pico_soff_155 2495
#define pico_soff_156 2504
#define pico_soff_157 2516
#define pico_soff_158 2522
#define pico_soff_159 2528
#define pico_soff_160 2560

#define PICO_STR_BLOB_INIT \
  0x626f7270,\
  0x206d656c,\
  0x64616572,\
  0x20676e69,\
  0x656c6966,\
  0x61656820,\
  0x00726564,\
  0x6d206f6e,\
  0x2065726f,\
  0x6e616874,\
  0x20692520,\
  0x6f736572,\
  0x65637275,\
  0x73250073,\
  0x73657200,\
  0x6372756f,\
  0x73252065,\
  0x206f6e00,\
  0x65726f6d,\
  0x61687420,\
  0x6925206e,\
  0x73657220,\
  0x6372756f,\
  0x70207365,\
  0x76207265,\
  0x6563696f,\
  0x206f6e00,\
  0x65726f6d,\
  0x61687420,\
  0x6925206e,\
  0x696f7620,\
  0x64206563,\
  0x6e696665,\
  0x6f697469,\
  0x7000736e,\
  0x6c626f72,\
  0x6c206d65,\
  0x6964616f,\
  0x6420676e,\
  0x75616665,\
  0x7220746c,\
  0x756f7365,\
  0x20656372,\
  0x6e007325,\
  0x6f6d206f,\
  0x74206572,\
  0x206e6168,\
  0x76206925,\
  0x6563696f,\
  0x6f760073,\
  0x20656369,\
  0x69666564,\
  0x6974696e,\
  0x25206e6f,\
  0x65720073,\
  0x72756f73,\
  0x25206563,\
  0x6f662073,\
  0x6f762072,\
  0x20656369,\
  0x25007325,\
  0x63610069,\
  0x203a6870,\
  0x726f6600,\
  0x20646563,\
  0x61726870,\
  0x65206573,\
  0x2700646e,\
  0x74737973,\
  0x20276d65,\
  0x20746f6e,\
  0x74696e69,\
  0x696c6169,\
  0x0064657a,\
  0x74737973,\
  0x6f206d65,\
  0x756f006b,\
  0x666f2074,\
  0x6d656d20,\
  0x2079726f,\
  0x61657263,\
  0x676e6974,\
  0x77656e20,\
  0x676e6520,\
  0x00656e69,\
  0x6d206f6e,\
  0x2065726f,\
  0x6e616874,\
  0x20692520,\
  0x69676e65,\
  0x0073656e,\
  0x676e6527,\
  0x27656e69,\
  0x746f6e20,\
  0x696e6920,\
  0x6c616974,\
  0x64657a69,\
  0x676e6500,\
  0x20656e69,\
  0x6e006b6f,\
  0x65626d75,\
  0x666f2072,\
  0x6e6f6c20,\
  0x756d2067,\
  0x6920746c,\
  0x64252073,\
  0x756e202c,\
  0x7265626d,\
  0x20666f20,\
  0x726f6873,\
  0x756d2074,\
  0x6920746c,\
  0x69252073,\
  0x6563000a,\
  0x64203a70,\
  0x6f66206f,\
  0x72617772,\
  0x74692064,\
  0x00206d65,\
  0x3a706563,\
  0x72700020,\
  0x656c626f,\
  0x7228206d,\
  0x69292d65,\
  0x6974696e,\
  0x7a696c61,\
  0x20676e69,\
  0x20656874,\
  0x69676e65,\
  0x7000656e,\
  0x6c626f72,\
  0x72206d65,\
  0x74657365,\
  0x676e6974,\
  0x676e6520,\
  0x00656e69,\
  0x6e6f6870,\
  0x20656d65,\
  0x75716573,\
  0x65636e65,\
  0x6f6f7420,\
  0x6e6f6c20,\
  0x25282067,\
  0x6e002973,\
  0x7220746f,\
  0x676f6365,\
  0x657a696e,\
  0x73612064,\
  0x61737820,\
  0x2061706d,\
  0x29732528,\
  0x6c6c6900,\
  0x61676165,\
  0x6870206c,\
  0x6d656e6f,\
  0x65732065,\
  0x6e657571,\
  0x28206563,\
  0x00297325,\
  0x706c6100,\
  0x65626168,\
  0x6f6e2074,\
  0x75732074,\
  0x726f7070,\
  0x20646574,\
  0x29732528,\
  0x554f4200,\
  0x4600444e,\
  0x454d4152,\
  0x5241505f,\
  0x4f485000,\
  0x4300454e,\
  0x4500444d,\
  0x46005252,\
  0x454d4152,\
  0x48544f00,\
  0x50005245,\
  0x00434e55,\
  0x4c4c5953,\
  0x4e4f4850,\
  0x524f5700,\
  0x41524744,\
  0x57004850,\
  0x4944524f,\
  0x5845444e,\
  0x524f5700,\
  0x4f485044,\
  0x5357004e,\
  0x475f5145,\
  0x48504152,\
  0x4b4e5500,\
  0x4e574f4e,\
  0x65685b00,\
  0x69206461,\
  0x554e2073,\
  0x005d4c4c,\
  0x7c63257c,\
  0x257c6325,\
  0x6e690069,\
  0x696c6176,\
  0x6e750064,\
  0x776f6e6b,\
  0x7265206e,\
  0x00726f72,\
  0x7400203a,\
  0x6d206f6f,\
  0x20796e61,\
  0x6e726177,\
  0x73676e69,\
  0x46495200,\
  0x41570046,\
  0x66004556,\
  0x0020746d,\
  0x61746164,\
  0x61772e00,\
  0x6e750076,\
  0x70707573,\
  0x6574726f,\
  0x69662064,\
  0x616e656c,\
  0x7320656d,\
  0x69666675,\
  0x6f6e0078,\
  0x6f632d6e,\
  0x726f666e,\
  0x676e696d,\
  0x61656820,\
  0x00726564,\
  0x6f636e65,\
  0x676e6964,\
  0x746f6e20,\
  0x70757320,\
  0x74726f70,\
  0x73006465,\
  0x6c706d61,\
  0x72662065,\
  0x65757165,\
  0x2079636e,\
  0x20746f6e,\
  0x70707573,\
  0x6574726f,\
  0x28200064,\
  0x53202943,\
  0x20584f56,\
  0x00204741,\
  0x6e6f7277,\
  0x756e2067,\
  0x7265626d,\
  0x726f6620,\
  0x0074616d,\
  0x626d756e,\
  0x65207265,\
  0x65656378,\
  0x00646564,\
  0x656d616e,\
  0x6e6f6320,\
  0x63696c66,\
  0x616e0074,\
  0x7520656d,\
  0x6665646e,\
  0x64656e69,\
  0x6c6c6900,\
  0x6c616765,\
  0x6d616e20,\
  0x75620065,\
  0x72656666,\
  0x65766f20,\
  0x6f6c6672,\
  0x75620077,\
  0x72656666,\
  0x646e7520,\
  0x6c667265,\
  0x6200776f,\
  0x65666675,\
  0x72652072,\
  0x00726f72,\
  0x2074756f,\
  0x6d20666f,\
  0x726f6d65,\
  0x61630079,\
  0x746f6e6e,\
  0x65706f20,\
  0x6966206e,\
  0x7500656c,\
  0x7078656e,\
  0x65746365,\
  0x69662064,\
  0x7420656c,\
  0x00657079,\
  0x72726f63,\
  0x20747075,\
  0x656c6966,\
  0x6c696600,\
  0x6f6e2065,\
  0x6f662074,\
  0x00646e75,\
  0x6f736572,\
  0x65637275,\
  0x20736920,\
  0x79737562,\
  0x6e616300,\
  0x20746f6e,\
  0x646e6966,\
  0x73657220,\
  0x6372756f,\
  0x6e6b0065,\
  0x656c776f,\
  0x20656764,\
  0x65736162,\
  0x73696d20,\
  0x676e6973,\
  0x63636100,\
  0x20737365,\
  0x6c6f6976,\
  0x6f697461,\
  0x6e69006e,\
  0x696c6176,\
  0x61682064,\
  0x656c646e,\
  0x6c617620,\
  0x69006575,\
  0x6c61766e,\
  0x61206469,\
  0x6d756772,\
  0x20746e65,\
  0x70707573,\
  0x6465696c,\
  0x646e6900,\
  0x6f207865,\
  0x6f207475,\
  0x61722066,\
  0x0065676e,\
  0x6568746f,\
  0x72652072,\
  0x00726f72,\
  0x6f727265,\
  0x6e692072,\
  0x6f727020,\
  0x73736563,\
  0x20676e69,\
  0x74696e75,\
  0x636e6900,\
  0x6c706d6f,\
  0x20657465,\
  0x7074756f,\
  0x75007475,\
  0x676e6973,\
  0x6c616620,\
  0x61622d6c,\
  0x6f006b63,\
  0x72656874,\
  0x72617720,\
  0x676e696e,\
  0x65766f00,\
  0x69727772,\
  0x676e6974,\
  0x6f6e6b20,\
  0x64656c77,\
  0x62206567,\
  0x00657361,\
  0x6f736572,\
  0x65637275,\
  0x726c6120,\
  0x79646165,\
  0x616f6c20,\
  0x00646564,\
  0x75706e69,\
  0x65762074,\
  0x726f7463,\
  0x746f6e20,\
  0x6e6f6320,\
  0x75727473,\
  0x64657463,\
  0x74756f00,\
  0x20747570,\
  0x20746f6e,\
  0x73616c63,\
  0x69666973,\
  0x6f006465,\
  0x75707475,\
  0x65762074,\
  0x726f7463,\
  0x746f6e20,\
  0x63656420,\
  0x6f706d6f,\
  0x00646573,\
  0x65727269,\
  0x616c7567,\
  0x74692072,\
  0x69206d65,\
  0x7270206e,\
  0x7365636f,\
  0x676e6973,\
  0x696e7520,\
  0x69640074,\
  0x72616373,\
  0x676e6964,\
  0x6f727020,\
  0x73736563,\
  0x20676e69,\
  0x74696e75,\
  0x66756220,\
  0x00726566,\
  0x3a6d6170,\
  0x72700020,\
  0x74756f20,\
  0x20666f20,\
  0x616e7964,\
  0x2063696d,\
  0x6f6d656d,\
  0x63007972,\
  0x65746e6f,\
  0x27207478,\
  0x20277325,\
  0x20746f6e,\
  0x6e756f66,\
  0x6e203b64,\
  0x6863206f,\
  0x65676e61,\
  0x6e616300,\
  0x20746f6e,\
  0x2070616d,\
  0x6e6f6870,\
  0x63697465,\
  0x72747320,\
  0x20676e69,\
  0x27732527,\
  0x7973203b,\
  0x6568746e,\
  0x697a6973,\
  0x7420676e,\
  0x20747865,\
  0x74736e69,\
  0x00646165,\
  0x6966005f,\
  0x2720656c,\
  0x20277325,\
  0x20746f6e,\
  0x6e756f66,\
  0x73203b64,\
  0x68746e79,\
  0x7a697365,\
  0x20676e69,\
  0x6c636e65,\
  0x6465736f,\
  0x78657420,\
  0x6e692074,\
  0x61657473,\
  0x00200064,\
  0x203a7270,\
  0x002f5c00,\
  0x41464544,\
  0x00544c55,\
  0x702d6173,\
  0x7300203a,\
  0x3a616e61,\
  0x68700020,\
  0x62206e6f,\
  0x65666675,\
  0x75662072,\
  0x73006c6c,\
  0x3a6f6870,\
  0x00730020,\
  0x7300736d,\
  0x3a786f76,\
  0x74746100,\
  0x74706d65,\
  0x206f7420,\
  0x20746573,\
  0x656c6c69,\
  0x206c6167,\
  0x756c6176,\
  0x69252065,\
  0x726f6620,\
  0x00732520,\
  0x616c6572,\
  0x65766974,\
  0x65707320,\
  0x66206465,\
  0x6f746361,\
  0x70730072,\
  0x00646565,\
  0x616c6572,\
  0x65766974,\
  0x74697020,\
  0x66206863,\
  0x6f746361,\
  0x69700072,\
  0x00686374,\
  0x616c6572,\
  0x65766974,\
  0x6c6f7620,\
  0x20656d75,\
  0x74636166,\
  0x7600726f,\
  0x6d756c6f,\
  0x65720065,\
  0x6974616c,\
  0x73206576,\
  0x6b616570,\
  0x66207265,\
  0x6f746361,\
  0x70730072,\
  0x656b6165,\
  0x69740072,\
  0x6600656d,\
  0x20656c69,\
  0x27732527,\
  0x746f6e20,\
  0x756f6620,\
  0x203b646e,\
  0x746e7973,\
  0x69736568,\
  0x676e697a,\
  0x636e6520,\
  0x65736f6c,\
  0x65742064,\
  0x69207478,\
  0x6574736e,\
  0x000a6461,\
  0x6e6e6163,\
  0x6d20746f,\
  0x70207061,\
  0x656e6f68,\
  0x20636974,\
  0x69727473,\
  0x2720676e,\
  0x3b277325,\
  0x6e797320,\
  0x73656874,\
  0x69657a69,\
  0x7420676e,\
  0x20747865,\
  0x74736e69,\
  0x00646165,\
  0x706d6973,\
  0x7420656c,\
  0x6e656b6f,\
  0x6f6f7420,\
  0x6e6f6c20,\
  0x66203b67,\
  0x6563726f,\
  0x72742064,\
  0x6d746165,\
  0x00746e65,\
  0x6b72616d,\
  0x74207075,\
  0x74206761,\
  0x6c206f6f,\
  0x00676e6f,\
  0x206f6f74,\
  0x796e616d,\
  0x74746120,\
  0x75626972,\
  0x20736574,\
  0x6d206e69,\
  0x756b7261,\
  0x69203b70,\
  0x726f6e67,\
  0x00676e69,\
  0x746e7973,\
  0x65207861,\
  0x726f7272,\
  0x206e6920,\
  0x6b72616d,\
  0x74207075,\
  0x6e656b6f,\
  0x73252720,\
  0x002e0027,\
  0x69666e75,\
  0x6873696e,\
  0x6d206465,\
  0x756b7261,\
  0x61742070,\
  0x25272067,\
  0x74002773,\
  0x003a6b6f,\
  0x6f6e6769,\
  0x76006572,\
  0x6563696f,\
  0x65727000,\
  0x636f7270,\
  0x746e6f63,\
  0x00747865,\
  0x6b72616d,\
  0x616c7000,\
  0x73750079,\
  0x67697365,\
  0x6e656700,\
  0x656c6966,\
  0x6e657300,\
  0x636e6574,\
  0x61700065,\
  0x72676172,\
  0x00687061,\
  0x72620070,\
  0x006b6165,\
  0x6c657073,\
  0x6870006c,\
  0x6d656e6f,\
  0x74690065,\
  0x6c006d65,\
  0x6c657665,\
  0x6d616e00,\
  0x72700065,\
  0x646f736f,\
  0x6d6f6479,\
  0x006e6961,\
  0x65646f6d,\
  0x00627300,\
  0x66006270,\
  0x00656c69,\
  0x65707974,\
  0x62306600,\
  0x66006765,\
  0x646e6530,\
  0x61667800,\
  0x65626564,\
  0x66780067,\
  0x65656461,\
  0x6100646e,\
  0x6168706c,\
  0x00746562,\
  0x6f006870,\
  0x6d687472,\
  0x0065646f,\
  0x6f6e6769,\
  0x75706572,\
  0x0074636e,\
  0x6f666e69,\
  0x6e690031,\
  0x00326f66,\
  0x6e697375,\
  0x64252067,\
  0x78656c20,\
  0x6e6f6369,\
  0x6f6f6c20,\
  0x2070756b,\
  0x75736572,\
  0x0073746c,\
  0x616e6177,\
  0x0000203a

#endif
